### ISSUE TITLE
Question: Reward of delegation

### ISSUE THREAD

**Issue by YuhsinLiao1995** [forbole/bdjuno#100]
is it possible to query the amount of reward by every single delegation?

![截圖 2021-02-09 上午10 34 33](https://user-images.githubusercontent.com/61954949/107308424-98d20600-6ac3-11eb-8459-614c11395cea.png)

**Comment by rmontagnin** [comment]
@YuhsinLiao1995 

You can get all the delegation rewards for a given validator with the following:

```graphql
query DelegationReward($height:bigint, $validator:String) {
  delegation_reward(where:{height:{_eq:$height}, validator_address:{_eq:$validator}}) {
    amount
  }
}
```

You can also get all the delegation rewards for all the validators:

```graphql
query DelegationReward($height:bigint) {
  delegation_reward(where:{height:{_eq:$height}}) {
    amount
  }
}
```

Finally, you can get all the delegation rewards for a given delegator: 

```graphql
query DelegationReward($height: bigint, $delegator: String) {
  delegation_reward(where: {height: {_eq: $height}, delegator_address: {_eq: $delegator}}) {
    delegator_address
    validator_address
    amount
  }
}
```

### Params
- `$validator` must be a validator address, starting with `cosmosvaloper1...`
- `$delegator` must be an account address, starting with `cosmos1...`
