### ISSUE TITLE
Support for new modules

### ISSUE THREAD

**Issue by faddat** [forbole/bdjuno#105]
Hi, bdjuno is great!

I am getting it rocking and rolling with gravity dex right now, and I've got a question --  the SQL schemas, are you writing those by hand, or generating them?

If you're generating them, mind if I ask how?

Armed with that, I think I may be able to improve the setup experience a little in the Readme.md

Cheers!

-Jacob

**Comment by rmontagnin** [comment]
Hi @faddat, and thanks! 

Currently, all the SQL schemes are defined by hand and not generated. This is because sometime you need custom things in order to let the tables interact properly between each other. I don't think it's worth exploring some generation stuff just because once you define a table it will most probably not change in the future. So creating a generator just to run it once appears to me a bit overpowered.

**Comment by faddat** [comment]
OK, I guess that I was thinking about using the generation to respond to changes as the chain is upgraded but also you're right because right now I'm just trying to push something out the door and time for me to do that and I just want to thank you very much for the reply-- also for bdjuno.


Currently I think that it works like this:

1) New chain is run, all standard modules are implemented in /x
2) Because bdjuno uses the cosmos-sdk, there's less of an issue with unmarshaling untyped returns.  Can use each module natively.  
3) Use the modules to query, and write their schema to postgres before starting
4) start the blockchain node
5) configure bdjuno with bdjuno init
6) start bdjuno with bdjuno parse ~/.gaia/config/config.toml
7)start graphql api using Hasura

Could you just let me know if I have any of that wrong or if I'm missing any important piece?

**Comment by rmontagnin** [comment]
@faddat That working flow is correct. I only have some difficulty understand, in point 3, what you mean with "Use the modules to query". Ideally, you don't need to do any by-hand queries before starting BDJuno. It will take care of everything pulling all the data into the PostgreSQL database by itself based on the configuration you use. Maybe I misunderstood what you meant though. 

**Edit**  
Also, one more thing. You don't need to run `bdjuno parse ~/.gaia/config/config.toml` anymore. You can leave the config argument and simply use `bdjuno parse`. It will take all the needed information from the configuration stored inside the `~/.bdjuno/config.toml` file.

**Comment by faddat** [comment]
Thank you @RiccardoM.  Closing this :).
