### ISSUE TITLE
Add validator avatar field to validator_info table

### ISSUE THREAD

**Issue by calvinkei** [forbole/bdjuno#107]
## Feature description 
In the current `validator_info` into, there's an `identity` field which is used for fetching the validator's avatar through keybase.io ([reference](https://github.com/forbole/big-dipper-default-interface/blob/fb25e185354753e85c6d177b980de0c83af87ed5/src/hooks/use_keybase_hook.tsx))

It will be better to include an `avatar` field in bdjuno directly for convenience

**Comment by rmontagnin** [comment]
@calvinkei I've added a `avatar_url` field inside the `validator_description` object. Example query: 

```graphql
query ValidatorDescriptions {
  validator_description(where:{avatar_url:{_is_null: false}}){
    avatar_url
  }
}
```

Example response: 

```json
{
  "data": {
    "validator_description": [
      {
        "avatar_url": "https://s3.amazonaws.com/keybase_processed_uploads/b2ea7f35809bbc65717e0d74ade0e705_360_360.jpg"
      },
      {
        "avatar_url": "https://s3.amazonaws.com/keybase_processed_uploads/c4c24fede7558bc316c8e69ff0b4b005_360_360.jpg"
      },
      {
        "avatar_url": "https://s3.amazonaws.com/keybase_processed_uploads/c62c205359734ddf9af1b03777703505_360_360.jpg"
      }
    ]
  }
}
```
