### ISSUE TITLE
Question: Hourly unbonding/ redelegation snapshots

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#109]
Currently there are unbonding/ redelegation snapshots happening hourly. I'm a bit confused as to how redelegations and unbondings are being logged. Can you clarify the following?

Since redelegation only happens on one height, my question is does the current snapshot record all redelegation whose completion time is still in the future at the height that the snapshot takes place?

ex:
- redelegation at `height: 95` `completion_time: before snapshot`
- redelegation at `height: 100` `completion_time: after snapshot`

- snapshot happens  at `height: 105`-

can i expect the following to be logged?
- redelegation at `height: 100` `completion_time: after snapshot`

The same question goes for unbondings

**Comment by rmontagnin** [comment]
All un/re/delegations are saved every hour as they appear on the chain. The completion time has no influence on whether a un/re/delegation is saved or not. This means that, in your case, that redelegation is expected to be logged.

If the snapshots happens at height `X`, all un/re/delegations at height `X` are stored in the database exactly as they appear on chain.
