### ISSUE TITLE
Log transaction events

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#123]
## Feature description 

Log transaction events so big dipper would be able to display how much a user withdraws etc

![image](https://user-images.githubusercontent.com/42913823/116563614-c5652380-a936-11eb-96d8-c00aadeb9b18.png)

**Comment by rmontagnin** [comment]
@ryuash Do you have other examples of things missing? These should be transactions not event

**Comment by rmontagnin** [comment]
@ryuash Just verified, and the `logs` field should already be there: 

```graphql
query Transaction {
  transaction(limit: 1) {
    logs
  }
}
```

**Comment by ryuash** [comment]
perfect
