### ISSUE TITLE
Calculate validator voting power percentage

### ISSUE THREAD

**Issue by RiccardoM** [forbole/bdjuno#13]
@kwunyeung Inside the requirements we find

> Calculate validator voting power percentage (staking) 

I've seen that the validator voting power can be fetched using the `/validatorsset/latest` API: 

http://lcd.morpheus.desmos.network:1317/validatorsets/latest

Is this sufficient or should it be fetched in another way?

**Comment by kwunyeung** [comment]
@RiccardoM Yes this can be done with this endpoint as it shows all corresponding voting power and you can calculate the total voting power of the network.

The existing `Big Dipper` is reading from `Tendermint` RPC as there was no such endpoint from REST server back then. We had to convert the consensus pubkey ourselves to map the validators from the validator set in `Tendermint` with the validator information in the state.

**Comment by RiccardoM** [comment]
@HarleyAppleChoi Can you please take into this? I think it's sufficient to implement an operation that runs every 1 minute that fetches that endpoint and stores the data into the database
