### ISSUE TITLE
Calculate validator self delegation ratio

### ISSUE THREAD

**Issue by RiccardoM** [forbole/bdjuno#14]
@kwunyeung inside the requirements we have

> Calculate validator self delegation ratio (staking)

Looking at the `x/staking` API the best one seems to be `/staking/validators?height=446016`: 

http://lcd.morpheus.desmos.network:1317/staking/validators?height=446016

For each validator, what I suppose we should do to compute the self delegation ratio is: 

`self_delefation_ration = tokens / delegator_shares * 100`

Is this correct?

**Comment by kwunyeung** [comment]
@RiccardoM The self delegation ratio is the how much the validator has self delegated from it's own delegator account. We need to know the self delegation address which you can convert it from the `desmosvaloper` address back to `desmos` prefix. Currently I save the self delegation address once a new validator appears on the network. And then query the `/staking/delegators/{delegatorAddr}/delegations/{validatorAddr}` endpoint. For example,

http://lcd.morpheus.desmos.network:1317/staking/delegators/desmos1835rcx9ahn0a62pfpufsfj7jwv0vfsw47tk7tz/delegations/desmosvaloper1835rcx9ahn0a62pfpufsfj7jwv0vfsw4qx72ps

Then you can get the number of shares or tokens the delegation has.

**Comment by HarleyAppleChoi** [comment]
I am doing a message handler approach that catches the MsgDelegate, every change of delegation. If that is from the self delegation address then safe it to table
It can also store the delegation from other accounts. Do we interested in that?

**Comment by RiccardoM** [comment]
@HarleyAppleChoi I'm currently implemented what you have suggested inside #18 so don't bother going after that. 

The way of handling `MsgDelegate` is perfect. Just make sure to also parse the genesis (you can do so by using a `GenesisHandler` so that you can get the starting data from when the chain spins up.
