### ISSUE TITLE
Proposal votes' voting period

### ISSUE THREAD

**Issue by rmontagnin** [forbole/bdjuno#140]
From #139 

There is a diagram which display vote result detail, it need to show `name`, `image`, `voting power%`, `voting power`, `voting power override` of every vote, now i use `voter_addess` to query  `validator_descriptions` from `Account`, but i do not find `voting power%`, `voting power`, `voting power override` in `Account` now, (1.)is it possible to add this info under `proposal_vote`?  (2.)besides, is the column `option` represent the answer of the voter? ex: `VOTE_OPTION_YES` for yes?

![截圖 2021-05-21 下午7 18 04](https://user-images.githubusercontent.com/61954949/119129307-524c5a00-ba69-11eb-92dc-c404517d1aaa.png)
```
query VoteDetail($proposal_id: Int!) {
  proposal_vote(where: {proposal_id: {_eq: $proposal_id}}) {
    voter_address
    proposal_id
    option
  }
}
```

**Comment by rmontagnin** [comment]
I need some help here from @kwunyeung and @ryuash to understand what are should the "Voting power" and "Voting power override" values represent. I can assume that the "Voting power" represents a single validator's voting power when they are voting, and I can think that the "Voting power override" represents an account voting power when they are voting differently from their validator(s). 



Now, what should it happen when an account has delegated to multiple validators? What should the values be?

**Comment by ryuash** [comment]
@YuhsinLiao1995 The voting power for this case is not something that can be done on the bdjuno layer as there are edge cases with the delegator voting themselves. I haven't implemented it yet, but I think what i would do is

1) get all the validator voting powers (we should be able to do this with one api call)
2) find all the delegators delegations and subtract the staked amount from the validator(s) voting powers accordingly (we will need multiple api calls for this)

**Comment by rmontagnin** [comment]
Closing this as it's not something related to BDJuno
