### ISSUE TITLE
BdJuno Lags behind

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#141]
## Bug description

Opening issue for track keeping.
Most days in the morning I noticed Bdjuno lags behind by a few thousand blocks. (Consensus is reading directly from the chain). Around noon/ tea time though, it will sync back up. I'm currently not sure why this happens

![image](https://user-images.githubusercontent.com/42913823/120415092-8c80fa00-c38d-11eb-8abc-14fc03c40f96.png)

**Comment by rmontagnin** [comment]
I'll use this issue as a place where to write all possible things that might make BDJuno lag behind. In the past days I've identified the following causes:

1. PostgreSQL database disk full
2. BDJuno daemon stops parsing 

I'll update with more comments when I find out with (2) is happening.

**Comment by rmontagnin** [comment]
#### Update
Today BDJuno stopped again. After checking, it was all fine (BDJuno was still running, Hasura too) except the database connection that dropped. I'm now thinking if this might be a Linode thing.

**Comment by rmontagnin** [comment]
#### Update  
Today BDJuno stopped again. I restarted it at block height `692,850` and it stopped at block height `729,980`.  
This is `37,130` blocks without interruption.

**Comment by mrlp4** [comment]
> **Update**
> Today BDJuno stopped again. I restarted it at block height `692,850` and it stopped at block height `729,980`.
> This is `37,130` blocks without interruption.

Have you found any more issues with db connection that time? 
And btw, do you have all things(bdjuno, hasura, postgres) on same machine or accessing db remotely?

**Comment by rmontagnin** [comment]
> Have you found any more issues with db connection that time?

Apparently, it's the db connection that is dropping. BDJuno was running fine (daemon was up) as well as Hasura and the PostgreSQL database itself. They were all up, just BDJuno was not communicating. 

> And btw, do you have all things(bdjuno, hasura, postgres) on same machine or accessing db remotely?
We have Hasura and BDJuno on the same server, and the PostgreSQL database is remote on another machine.

**Comment by rmontagnin** [comment]
#### Update  
BDJuno stopped again on block `743,625`. This is `13,645` blocks after the previous stop. It seems to become more frequent over time. 

**Edit**  
This time it was a Desmos error related to the node we use to get the chain data. I've opened an issue here: tendermint/tendermint#6607

**Comment by rmontagnin** [comment]
#### Update
BDJuno stopped again on block `821,369`. This is `77,744` blocks without interruption.  
It seems that stops are random.

**Comment by rmontagnin** [comment]
#### Update 
BDJuno stopped again on block `843,381`. This is `22,012` blocks without interruption.

**Comment by rmontagnin** [comment]
#### Update
BDJuno stopped again on block `906,002`. This is `62,621` blocks without interruption.

**Comment by ryuash** [comment]
I think we've been pretty stable. Okay to close and open again if needed?

**Comment by rmontagnin** [comment]
> I think we've been pretty stable. Okay to close and open again if needed?

Sure

**Comment by rach-id** [comment]
@ryuash Hello, I am facing almost the same issue with `bdjuno`, except that for me, it's only lagging behind for a hundred block.
When I restart `bdjuno`, it seems to work fine until it starts slowing down significantly.
Also, `postgres` is eating tons of resources with multiple connections.
My setup consists of `hasura`, `big dipper` and `bdjuno` on the same machine (8 cores 16 GB machine) and the node is on a separate instance (it is up-to-date with the chain).
I tried increasing the number of workers for `bdjuno`, increase the number of connections to `postgres`, but still not able to keep up for a long period.

Is there something specific you did for it to be stable ? 
Thanks
