### ISSUE TITLE
queries of `delegation_reward_histories_aggregate` takes forever to load

### ISSUE THREAD

**Issue by calvinkei** [forbole/bdjuno#143]
## Bug description
Below is the query I'm making:
```
query AccountBalance {
    account(where: { address: { _eq: "desmos1hazqvj7ketp3svxhc2cx0pz6t2chk9hte9p33s" } }) {
      address
      available: account_balance_histories(limit: 1, order_by: { height: desc }, where: { height: { _lte: 716340 } }) {
        coins
        height
        block { timestamp }
        tokens_prices: token_prices_history {
          unit_name
          price
          timestamp
          token_unit {
            denom
            exponent
            token {
              token_units {
                denom
                exponent
              }
            }
          }
        }
      }
      delegated: delegation_histories_aggregate(distinct_on: [validator_address], order_by: [{validator_address: desc}, {height: desc}], where: { height: { _lte: 716340 } }) {
        nodes {
          amount
          validator_address
        }
      }
      unbonding: unbonding_delegation_histories_aggregate(distinct_on: [validator_address], order_by: [{validator_address: desc}, {height: desc}], where: { height: { _lte: 716340 } }) {
        nodes {
          amount
          completion_timestamp
          height
          validator_address
        }
      }
      rewards: delegation_reward_histories_aggregate(distinct_on: [validator_address], order_by: [{validator_address: desc}, {height: desc}], where: { height: { _lte: 716340 } }) {
        nodes {
          amount
          validator_address
        }
      }
      validator: validator_infos(where: {self_delegate_address: {_eq: "desmos1hazqvj7ketp3svxhc2cx0pz6t2chk9hte9p33s"}}) {
        consensus_address
        operator_address
        self_delegate_address
        validator {
          commissions: validator_commission_amount_histories_aggregate(limit: 1, order_by: {height: desc}, where: { height: { _lte: 716340 } }) {
            nodes {
              amount
            }
          }
        }
      }
    }
  }
```
It takes forever to load and returns CORS error after timeout. The same query works when I removed the `delegation_reward_histories_aggregate` part, ie:
```
query AccountBalance {
    account(where: { address: { _eq: "desmos1hazqvj7ketp3svxhc2cx0pz6t2chk9hte9p33s" } }) {
      address
      available: account_balance_histories(limit: 1, order_by: { height: desc }, where: { height: { _lte: 716340 } }) {
        coins
        height
        block { timestamp }
        tokens_prices: token_prices_history {
          unit_name
          price
          timestamp
          token_unit {
            denom
            exponent
            token {
              token_units {
                denom
                exponent
              }
            }
          }
        }
      }
      delegated: delegation_histories_aggregate(distinct_on: [validator_address], order_by: [{validator_address: desc}, {height: desc}], where: { height: { _lte: 716340 } }) {
        nodes {
          amount
          validator_address
        }
      }
      unbonding: unbonding_delegation_histories_aggregate(distinct_on: [validator_address], order_by: [{validator_address: desc}, {height: desc}], where: { height: { _lte: 716340 } }) {
        nodes {
          amount
          completion_timestamp
          height
          validator_address
        }
      }
      validator: validator_infos(where: {self_delegate_address: {_eq: "desmos1hazqvj7ketp3svxhc2cx0pz6t2chk9hte9p33s"}}) {
        consensus_address
        operator_address
        self_delegate_address
        validator {
          commissions: validator_commission_amount_histories_aggregate(limit: 1, order_by: {height: desc}, where: { height: { _lte: 716340 } }) {
            nodes {
              amount
            }
          }
        }
      }
    }
  }
```

**Comment by rmontagnin** [comment]
@calvinkei After analyzing your query I think there are two main problems: 

1. You are using the `delegation_histories_aggregate` table even when not needed. This causes the database to perform more operations even when they are not needed at all. For this reason, I think it would be much better to use the `delegation_histories` table and remove the `nodes` field instead. 
2. You are not limiting the results. This causes the database to iterate over all the returned rows to transform them into JSON objects that are later inserted inside the JSON array. For this reason, I suggest you limiting the results.

Unfortunately, there seem to be no other solutions than these two

**Comment by calvinkei** [comment]
@RiccardoM the performance issue is probably not related to `delegation_histories_aggregate` table, but `delegation_reward_histories_aggregate`. i removed the query related to `delegation_reward_histories_aggregate` and it loads within 200ms

also, since the results are distinct on validator, so i think it doesn't have to limit the results. it should just take the latest row for each validator. which makes sense as i want to know the total delegated amount across different validators

**Comment by calvinkei** [comment]
FYI, the same issue goes for `delegation_reward_histories` table (without aggregate). btw thanks for reminding the unnecessary use of aggregate table. i will change those queries

**Comment by rmontagnin** [comment]
@calvinkei Sorry for the confusion, I meant to write `delegation_reward_histories_aggregate` in my original answer but then copy/pasted the wrong name. I made all my tests with `delegation_reward_histories_aggregate` and I saw that if you add the limit it should load it faster. The problem is that since that's a history table, it exists a row for each block-validator-delegator touple. Do you mind explaining further why you need such data? Do you need it to show the current delegation rewards, or to show a history of them?

**Comment by calvinkei** [comment]
@RiccardoM I'm using the data to show a line chart of account balance changes over time. the data needs to include available balance, delegated amount, rewards and commission at each specific timestamp

is there a way to get the sum of rewards for all validators at a specific timestamp?

**Comment by rmontagnin** [comment]
@calvinkei Do you need those data to be shown in different graphs (i.e. one for the available balance, one for the delegated amount, one for the rewards, etc), or do you need them to be shown together? 

I'm thinking that maybe what we can do is have a single table instead of multiple ones that return those data as different columns. This might make it faster for you to get

**Comment by calvinkei** [comment]
@RiccardoM that would be perfect! for latest data i need to show it separately but for historical data i just need the sum, ie 1 single chart
