### ISSUE TITLE
ERROR: pq: syntax error at or near "VALUE"

### ISSUE THREAD

**Issue by lightiv** [forbole/bdjuno#176]
## Bug description

From the akash branch: Starting 'bdjuno parse' results in the following error:

ERROR: pq: syntax error at or near "VALUE"

## Steps to reproduce
 
From the akash branch:  run 'bdjuno parse'

**Comment by rmontagnin** [comment]
This is not enough data to understand what is happening. 

1.Are there any correlated errors that are shown? 
2. What operation is being performed whdn this happens?

We need more details

**Comment by rmontagnin** [comment]
Fixed with 1c7051dc81ca04e0dbd7080a4d3c7bc4896163cd
