### ISSUE TITLE
Update to Cosmos v0.43.0

### ISSUE THREAD

**Issue by rmontagnin** [forbole/bdjuno#178]
Now that Cosmos [`v0.43.0`](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.43.0) has been released, we should update BDJuno to support this version too. The updated should be done on a new branch (`cosmos/v0.43.x`) as this version brings major changes in vary different modules. The CHANGELOG should be read carefully to determine what it needs to change (if anything).

**Comment by fedekunze** [comment]
This PR adds support for v0.43 to Juno: https://github.com/RiccardoM/juno/pull/25

**Comment by rmontagnin** [comment]
Thanks @fedekunze, I've now created a new branch to support Cosmos v0.43.x: [`cosmos/v0.43.x`](https://github.com/forbole/bdjuno/tree/cosmos/v0.43.x)
