### ISSUE TITLE
Add Ethermint support

### ISSUE THREAD

**Issue by fedekunze** [forbole/bdjuno#179]
## Feature description 

Add [Ethermint](https://github.com/tharsis/ethermint) dependencies for BigDipper ([`v0.5.0`](https://github.com/tharsis/ethermint/releases/tag/v0.5.0))

## Implementation proposal

NOTE: Ethermint uses SDK `v0.43.0` so I guess it's blocked by #178

**Comment by rmontagnin** [comment]
This has now been added to the [`chains/ethermint`](https://github.com/forbole/bdjuno/tree/chains/ethermint) branch
