### ISSUE TITLE
Inconsistent object: environment variable 'HASURA_GRAPHQL_DATABASE_URL' not set

### ISSUE THREAD

**Issue by toschdev** [forbole/bdjuno#186]
When I want to run Hasura GraphQL I get the following error message

`Inconsistent object: environment variable 'HASURA_GRAPHQL_DATABASE_URL' not set`

## Bug description
Environmental variable not set

## Steps to reproduce
Import `hasura` directory into Hasura via CLI or the Cloud

## Expected behavior
In the documentation there should be a section on how or where to set the HASURA_GRAPHQL_DATABASE_URL

**Comment by toschdev** [comment]
In the cloud I can set this in .env vars

![Bildschirmfoto 2021-09-03 um 21 13 40](https://user-images.githubusercontent.com/8368497/132055688-df931ff2-8a46-4e33-89d0-66c22723dd11.png)

**Comment by toschdev** [comment]
How would I do it in the CLI?

**Comment by rmontagnin** [comment]
You need to set it while starting your Docker container: 

```shell
docker run ... -e "HASURA_GRAPHQL_DATABASE_URL=..."
```
