### ISSUE TITLE
Inconsistent Metadata on the desmos-mainnet branch

### ISSUE THREAD

**Issue by lightiv** [forbole/bdjuno#187]
## Bug description

I am receiving the following error when importing the metadata

block	object_relation	relationship of table "proposal_vote":
Inconsistent object: in table "proposal_vote": in relationship "block": no foreign constraint exists on the given column

block	object_relation	relationship of table "proposal_deposit":
Inconsistent object: in table "proposal_deposit": in relationship "block": no foreign constraint exists on the given column

## Steps to reproduce
 

Import the metadata

## Expected behavior

Metadata will import without error

**Comment by rmontagnin** [comment]
I have updated all the metadata on all branches, thanks! They should work now.
