### ISSUE TITLE
desmos: MsgAcceptTransferRequest not handled properly

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#193]
## Bug description

One the Dtag is transferred bdjuno does not update the previous owner with the new Dtag.
https://explorer.desmos.network/accounts/desmos1a5v9a94edq686aesyf4ufrdedwjpn8jflv4mwc
https://explorer.desmos.network/accounts/desmos12jhz5njn5tz0yymr0amtynnzdq6ne3n0aucc4w

both accounts are listing as the owner of blastoise but in reality desmos12jhz5njn5tz0yymr0amtynnzdq6ne3n0aucc4w owns charizard

## Steps to reproduce
 
- create 2 address `user-1` `user-2`
- `user-1` make profile
- `user-2` request `user-1` profile
- `user-1` accept transfer and creates a new dtag

**Comment by rmontagnin** [comment]
This is handled by DJuno, please open it there: [desmos-labs/djuno](http://github.com/desmos-labs/djuno)

**Comment by rmontagnin** [comment]
Moved to desmos-labs/djuno#9
