### ISSUE TITLE
`block` field is missing on `proposal_deposit` for mainnet

### ISSUE THREAD

**Issue by calvinkei** [forbole/bdjuno#195]
## Bug description
`block` field is missing on `proposal_deposit` for mainnet, but it presents on testnet

<img width="434" alt="Screenshot 2021-09-16 at 12 47 38 AM" src="https://user-images.githubusercontent.com/14106911/133475755-9d44a9fe-9ea9-4e73-81a0-84f399088963.png">
<img width="377" alt="Screenshot 2021-09-16 at 12 47 55 AM" src="https://user-images.githubusercontent.com/14106911/133475766-d0e8dead-3890-4208-9ce8-87b5fa26af8d.png">

**Comment by rmontagnin** [comment]
This has been fixed now
