### ISSUE TITLE
validator details imageurl not updated properly

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#196]
## Bug description

I suspect once a validator updates their validator details the imageurl becomes null. This has happened to cat boss once and i noticed OranG3cluB recently updated their validator details and now their imageurl is null while previously having an orange.

**Comment by rmontagnin** [comment]
Should have been fixed with f88d1be7731ca9b309dd2822a705ee65f56c9830. Waiting for confirmation before closing this
