### ISSUE TITLE
bug: redelegations not being handled properly for rewards

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#197]
## Bug description

- delegate to validator A. Wait a day for rewards to accumilate
- redelegate to validator B
- even thought rewards were withdrew by redelegation bdjuno did not properly handle it thus causing rewards from validator A to still exist.

I will create a temporary fix on the frontend.

**Comment by rmontagnin** [comment]
Should have been fixed with ce94380e8aad818a7c1445cbe492ed3e898c5a08. Waiting for confirmation before closing this
