### ISSUE TITLE
[e-Money] Wrong average block time on e-Money

### ISSUE THREAD

**Issue by kwunyeung** [forbole/bdjuno#201]
Average block time on `e-Money` is now extremely huge as the value is calculated by the difference from current time to genesis  time. We should take the consensus time of block 1 on `e-Money` instead to give a more reasonable average block time.

![image](https://user-images.githubusercontent.com/932636/134123280-07b7f436-bd41-49c0-bca1-2afbbeee0a1b.png)

**Comment by huichiaotsou** [comment]
Hi @kwunyeung , in Hasura the time of block 1 is the same as the genesis time. 

As now we are rendering the time from the table "average_block_time_from_genesis", maybe it would be reasonable to use the time "average_block_time_per_hour" ?

**Comment by kwunyeung** [comment]
@huichiaotsou ah that sounds suitable for e-money.

**Comment by ryuash** [comment]
Ok no need to change anything in bdjuno then. I will update this on the ui
