### ISSUE TITLE
[LikeCoin] Proposal votes mismatch

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#208]
## Bug description

Last checked likecoin's latest proposal had 69 votes but bdjuno was only able to log 9 of those. Would we be able to run a script that runs through the blocks and log only msgVote so that the proposal is correctly caught up?

**Comment by ryuash** [comment]
@RiccardoM  will the current proposals on LikCcoin be updated to fix the mismatch?

**Comment by rmontagnin** [comment]
@ryuash Yes, we can upgrade Likecoin to use the new version that includes the following command: 
```
bdjuno fix gov proposal [id]
```

Once the new version is installed, we simply have to run that command and the whole data about that proposal should be re-fetched from the node and re-stored inside the database fixing any problem.

This should obviously be run for each proposal that should be fixed.

**Comment by ryuash** [comment]
@MonikaCat can you handle this :O would love to see likecoin proposals get fixed
