### ISSUE TITLE
Handle MsgWithdrawDelegatorReward and MsgWithdrawValidatorCommission

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#215]
## Feature description 

Because we are no longer getting rewards at every block when a user MsgWithdrawDelegatorReward/ MsgWithdrawValidatorCommission the rewards are not correctly updated right away. We see a lag in the ui that can be very misleading.
## Implementation proposal

If a user runs MsgWithdrawDelegatorReward we should update the rewards

**Comment by kwunyeung** [comment]
The accounts should be read from the events as the withdraw address may not be the same as the sender address.

**Comment by ryuash** [comment]
I don't know if this has been merged in to desmos bdjuno yet but I tested it out three times this morning and the commission updated right away but the rewards took another 1-3minutes before updating

Most likely related but the staking tab also isn't updated on these changes:
![image](https://user-images.githubusercontent.com/42913823/137056278-8a095db3-dcd1-4f1e-a6ae-d59fc92e975d.png)


Feel free to close again if this has been fixed and tested

**Comment by huichiaotsou** [comment]
deployed by Monika
