### ISSUE TITLE
Blocks and transactions are skipped sometimes

### ISSUE THREAD

**Issue by kwunyeung** [forbole/bdjuno#216]
## Bug description

This happens on LikeCoin BD. The prop#16 was passed. There were 81 vote transactions for prop#16 but only 8 votes were indexed in the database.

https://likecoin.bigdipper.live/proposals/16

Blocks are missing sometimes. There are reports on BitCanna.

![image.png](https://images.zenhubusercontent.com/610d12dcbed147b45e407c24/9ab29e4c-dc53-491f-a710-aa808918b7c6)

Possible to avoid missing blocks being indexed? How about if a block is failed to be indexed at some point, `BDJuno` would retry?

**Comment by kwunyeung** [comment]
Transaction issue is mentioned in #208 as well.

**Comment by rmontagnin** [comment]
> Possible to avoid missing blocks being indexed? How about if a block is failed to be indexed at some point, `BDJuno` would retry?

I don't understand what you mean with this. If BDJuno doesn't catch some blocks, they won't be indexed. 

And if there are some errors while parsing the blocks, it will log those errors and try again later until the block is parsed.

**Comment by MonikaCat** [comment]
Closed with #248
