### ISSUE TITLE
Balance not updated once unbonding delegation ends

### ISSUE THREAD

**Issue by rmontagnin** [forbole/bdjuno#217]
## Bug description
Once an unbonding delegation ends, the balance is not updated. 

## Steps to reproduce
1. Delegate some tokens to a validator.
2. Unbond those tokens.
3. Wait for the unbonding to end. 
4. Observe your balance.

## Expected behavior

Once the delegation has been undonded, the balance should update with the amount of tokens.

**Comment by MonikaCat** [comment]
Closed with #251
