### ISSUE TITLE
price_feed error

### ISSUE THREAD

**Issue by lightiv** [forbole/bdjuno#224]
## Bug description

Oct 08 05:37:28 systemd[1]: Started BDJuno Parser.
Oct 08 05:37:28 bdjuno[128244]: 5:37AM DBG storing tokens module=pricefeed
Oct 08 05:37:28 bdjuno[128244]: ERROR: error while saving token: error while saving token: pq: column "price_id" of relation "token_unit" does not exist
Oct 08 05:37:28 systemd[1]: bdjuno.service: Main process exited, code=exited, status=1/FAILURE

## Steps to reproduce
 

Compile origin/cosmos/v0.44.x and run bdjuno.  You will receive the error above.  To get past this I removed the price_feed section in config.toml

**Comment by rmontagnin** [comment]
This is due to the fact that we added a `price_id` field to our `pricefeed` configuration. Please refer to [this](https://docs.bigdipper.live/cosmos-based/parser/config#pricefeed) to know more
