### ISSUE TITLE
ERROR: flag accessed but not defined: replace

### ISSUE THREAD

**Issue by lightiv** [forbole/bdjuno#234]
## Bug description

Receiving this error when building and running a default  repo branch: https://github.com/forbole/bdjuno/tree/v2/cosmos%2Fstargate

```
bdjuno init
 
ERROR: flag accessed but not defined: replace
```
It did not recognize the already initialized directory if you attempted to run the newly build binary.

## Steps to reproduce
 

Clone and make install and then attempt to initialize the derectory.

## Expected behavior

The binary to build and run properly.

I am using go version: go1.17.1 linux/amd64

**Comment by rmontagnin** [comment]
Fixed with `f619ac3a5de1a473e3a19b5340b487bb7125d3ff`
