### ISSUE TITLE
`fix gov proposal` throws error on older proposals

### ISSUE THREAD

**Issue by MonikaCat** [forbole/bdjuno#245]
## Bug description

When running ```bdjuno fix gov proposal``` for proposal 16 and 17, bdjuno throws error:

```ERROR: error while handling MsgDeposit: error while getting proposal deposit: rpc error: code = InvalidArgument desc = rpc error: code = InvalidArgument desc = depositer: cosmos1f90nyyptfajz58m9sa9dygwajwuxkv83zq5k9j not found for proposal: 16: invalid request``` 
## Steps to reproduce
 
1. Run ```bdjuno fix gov proposal 16``` on Likecoin
2. See the error 

## Expected behavior

The proposal deposits should be stored/updated in db

**Comment by rmontagnin** [comment]
This has actually been found out to be an error in the Likecoin node we were using. The node was not setup to be an archive node (`pruning = nothing`) and so it was not able to properly get the data. Running this command on an archive node will fix the problems.
