### ISSUE TITLE
Redelegation not updating balance

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#268]
By default, when a user redelegates from validator A to validator B rewards withdrawn is made automatically. I believe bdjuno currently does not handle this properly.

Expectation:
User redelegates and withdrawn rewards are shown up in the balance

**Comment by rmontagnin** [comment]
Did you try this with an account that had a different `reward_address` set? Or with a normal account?

**Comment by ryuash** [comment]
Rachel reported this. Should have the same rewards address

**Comment by MonikaCat** [comment]
Is this issue still valid? I cannot reproduce the bug. I redelegated from validator A to validator B and the rewards have been added correctly to the total available amount after the tx has been broadcasted (tested on X with the same rewards address as my account)
