### ISSUE TITLE
Token price and market cap

### ISSUE THREAD

**Issue by RiccardoM** [forbole/bdjuno#27]
## Feature description 
We need to implement the ability of fetching every 30 seconds the token price and market cap. 

## Implementation proposal
I think that the token denomination can be easily get from the `/staking/parameters` endpoint, taking the `bond_denom` denomination. 

@kwunyeung do you have any preference from where to get the data? Do you know any API that might allow us to fetch it?

**Comment by kwunyeung** [comment]
We use Coingecko API

https://www.coingecko.com/api/documentations/v3

**Comment by HarleyAppleChoi** [comment]
Do we take market cap and token price from this endpoint? What do we put in ids attribute?
[https://api.coingecko.com/api/v3/coins/markets?vs_currency=eur&ids=10x-long-bitcoin-cash-token&order=market_cap_desc&per_page=100&page=1&sparkline=false
](url)
Do we need to modify Juno in order to handle queries from this API?

**Comment by RiccardoM** [comment]
@HarleyAppleChoi Looking at the different CoinGecko APIs and what they return, I think we could do it in the following way. 

First of all, we need the coin ID as you saw. To get this what we can do is use the [`/coins/list` API](https://www.coingecko.com/api/documentations/v3#/coins/get_coins_list). It should return an array inside which object is formed as follows: 

```json
{
  "id": "<Coin ID>",
  "symbol": "<Coin symbol>",
  "name": "<Coin name>"
}
```
([Example](https://api.coingecko.com/api/v3/coins/list))

Now, having such array, we can search the coin having the name equals to the value of the `bond_denom` staking parameter. Once we found that, we can get its ID.

Once we have that ID, we can use the API you've mentioned ([`/coins/markets/`]()) with the following query parameters: 

```
/coins/markets?vs_currency=usd&ids=bitcoin
```

([Example - Bitcoin](https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=bitcoin))

This should return a result similar to this one: 

```json
[
  {
    "id": "bitcoin",
    "symbol": "btc",
    "name": "Bitcoin",
    "image": "https://assets.coingecko.com/coins/images/1/large/bitcoin.png?1547033579",
    "current_price": 9528.15,
    "market_cap": 175778017378,
    "market_cap_rank": 1,
    "total_volume": 36313652382,
    "high_24h": 9619.81,
    "low_24h": 9463.45,
    "price_change_24h": 22.81,
    "price_change_percentage_24h": 0.23999,
    "market_cap_change_24h": 509106243,
    "market_cap_change_percentage_24h": 0.29047,
    "circulating_supply": 18441006,
    "total_supply": 21000000,
    "ath": 19665.39,
    "ath_change_percentage": -51.52952,
    "ath_date": "2017-12-16T00:00:00.000Z",
    "atl": 67.81,
    "atl_change_percentage": 13956.99896,
    "atl_date": "2013-07-06T00:00:00.000Z",
    "roi": null,
    "last_updated": "2020-07-24T12:04:59.803Z"
  }
]
```

Now, all we have to do is take the `current_price` value and we should be good to go :grin:
