### ISSUE TITLE
Validator VP not updating when status changes

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#270]
Reference: https://explorer.desmos.network/validators/desmosvaloper1t4urajq9xw4fppld2dl3xzwxqjkmjx9zfv3q5u
When a validator's status goes to unbonding or unbonded we should update the VP to 0. Currently it stays at the last block they signed i believe

**Comment by ryuash** [comment]
@RiccardoM would we be able to run this once on desmos mainnet for the existing inactive validators?

![image](https://user-images.githubusercontent.com/42913823/145173403-23144bb4-24bb-49b2-a078-0e704930c2af.png)

**Comment by rmontagnin** [comment]
@ryuash As soon as the Desmos version of BDJuno is updated with this change, the voting power should immediately change after one block since it's updated on a per-block basis. All those validators should then show 0
