### ISSUE TITLE
[Secret Network] Secret Network support with BigDipper2.0

### ISSUE THREAD

**Issue by mohammedpatla** [forbole/bdjuno#273]
## Feature description 
Looking to have secret network integrated with Bigdipper. Implementation for that would be useful.

## Implementation proposal
With the new supernova upgrade, secret is at 0.44.x SDK version. This should mean that with the correct endpoints we should be able to directly port existing chains like terra to work with secret.

We do have a testnet node we can provide endpoints to and the public mainnet endpoints are at https://api.scrt.network/

**Comment by ryuash** [comment]
We have documentations for a custom chain setup available here: https://docs.bigdipper.live/

Is there any specific questions you need help with for the setup?

**Comment by mohammedpatla** [comment]
Hey @ryuash I have been trying to use custom setup here [link](https://github.com/mohammedpatla/bdjuno/blob/v2/chains/secretnetwork/cmd/bdjuno/main.go) but when I try to parse the bdjuno i get 
`ERROR: failed to start client: dial tcp [::1]:26657: connect: connection refused`

I cross-checked the endpoints on our nodes working fine with other applications: http://testnet.securesecrets.org:26657 

Here is the config I use for the YAML. Please advise.

> chain:
>     bech32_prefix: secret
>     modules: 
>         - modules
>         - messages
>         - auth
>         - gov
>         - staking
> node:
>     type: remote
>     config:
>         rpc:
>             client_name: pulsar
>             address: http://testnet.securesecrets.org:26657
>             max_connections: 20
>         grpc:
>             address: http://testnet.securesecrets.org:9090
>             insecure: true
> parsing:
>     workers: 1
>     listen_new_blocks: true
>     parse_old_blocks: true
>     parse_genesis: false
>     start_height: 1
>     fast_sync: true
>     genesis_file_path: /root/genesis.json
> database:
>     name: mydb
>     host: localhost
>     port: 5432
>     user: postgres
>     password: *********
>     schema: public
>     max_open_connections: 10
>     max_idle_connections: 10
> logging:
>     level: debug
>     format: text
> telemetry:
>     port: 5000
> pruning:
>     keep_recent: 100
>     keep_every: 500
>     interval: 10
> pricefeed:
>     tokens:
>         - name: secret
>           units:
>             - denom: uscrt
>               exponent: 0
>             - denom: scrt
>               exponent: 6
>               price_id: secret
> distribution:
>     rewards_frequency: 100

edit:
I should note that when i was making the file i did see one dependency cause an issue:
>go: github.com/forbole/tendermint@v0.34.13-0.20211005074050-33591287eca5: parsing go.mod:
>        module declares its path as: github.com/tendermint/tendermint
>               but was required as: github.com/forbole/tendermint
>go: github.com/forbole/tendermint@v0.34.13-0.20211005074050-33591287eca5: parsing go.mod:
>        module declares its path as: github.com/tendermint/tendermint
>                but was required as: github.com/forbole/tendermint
>make: *** [Makefile:41: install] Error 1

**Comment by ryuash** [comment]
I believe the config requires the ip for gRPC and RPC. @MonikaCat would you be able to confirm?

**Comment by mohammedpatla** [comment]
After changing it to IP it still does not fix it showing the same connection refused.
`
config:
        rpc:
            client_name: pulsar
            address: http://144.202.126.98:26657
            max_connections: 20
        grpc:
            address: http://144.202.126.98:9090
            insecure: true
            
`

**Comment by huichiaotsou** [comment]
Hi @mohammedpatla, 

Hope you're doing fine. 

Is your issue solved? I am using the [same config.yaml](https://pastebin.com/N4w6MxA5) as yours above, and I am able to run **bdjuno parse**. Would you mind checking if you are on the right bdjuno branch **v2/cosmos/stargate** and make install again ? 

![Screen Shot 2021-11-30 at 10 45 39 AM](https://user-images.githubusercontent.com/76254323/143976710-62a1b108-f7dd-4084-bb1e-27a032317e5f.png)

**Comment by mohammedpatla** [comment]
@huichiaotsou not sure when i fork it with S/N go modules on the stargate branch i never get it to successfully compile.
https://github.com/mohammedpatla/bdjuno/tree/v2/cosmos%2Fsecret

**Comment by huichiaotsou** [comment]
> 

Hi @mohammedpatla , would you mind showing your errors? I could successfully compile with the codes from your fork and parsed with success. 

try running **go get github.com/forbole/tendermint** ?

**Comment by MonikaCat** [comment]
Using IP in config file is not necessary, as long as the ports are correct. @mohammedpatla since you mentioned secret network is at 0.44.x SDK version, you should be using v2/cosmos/v0.44.x branch. Can you try it and let us know if it worked?

**Comment by mohammedpatla** [comment]
hey @huichiaotsou @MonikaCat 
I have both those versions i am trying to compile. I am surprised you got that running at all,c ould it be go versions? i am on `go version go1.17.3 linux/amd64`

For the branch cosmos/secret -> based v2/cosmos/stargate i get
```
fatal: No names found, cannot describe anything.
installing bdjuno binary...
```

Inside chains/secretnetwork branch -> based on v2/cosmos/v0.44.x i get the following issue.

```
fatal: No names found, cannot describe anything.
installing bdjuno binary...
go: github.com/forbole/tendermint@v0.34.13-0.20211005074050-33591287eca5: parsing go.mod:
        module declares its path as: github.com/tendermint/tendermint
                but was required as: github.com/forbole/tendermint
go: github.com/forbole/tendermint@v0.34.13-0.20211005074050-33591287eca5: parsing go.mod:
        module declares its path as: github.com/tendermint/tendermint
                but was required as: github.com/forbole/tendermint
make: *** [Makefile:41: install] Error 1
```
https://github.com/mohammedpatla/bdjuno

running go get gives me
```
root@vultr:~/bdjuno# go get github.com/forbole/tendermint
go: github.com/forbole/tendermint@v0.34.13-0.20211005074050-33591287eca5: parsing go.mod:
        module declares its path as: github.com/tendermint/tendermint
                but was required as: github.com/forbole/tendermint 
```

**Comment by MonikaCat** [comment]
Hi @mohammedpatla I pulled your repo and tested it locally with the config you provided above and bdjuno runs with no errors. Did you try to run `go mod tidy` before running `make install` ?

**Comment by mohammedpatla** [comment]
@MonikaCat yup still the same issue. 
```
root@vultr:~/bdjuno# go mod tidy
go: github.com/forbole/tendermint@v0.34.13-0.20211005074050-33591287eca5: parsing go.mod:
        module declares its path as: github.com/tendermint/tendermint
                but was required as: github.com/forbole/tendermint
go: downloading github.com/proullon/ramsql v0.0.0-20181213202341-817cee58a244
go: github.com/forbole/tendermint@v0.34.13-0.20211005074050-33591287eca5: parsing go.mod:
        module declares its path as: github.com/tendermint/tendermint
                but was required as: github.com/forbole/tendermint
```

You might have it locally installed from another branch perhaps i am missing them?

looks like a go issue - what version are you running on? I will think about dockerizing this whole thing, so don't run into go dependencies issues. Even better getting the whole db as a docker with hashura and front-end as 3 different docker containers would be interesting and easy to maintain.

**Comment by MonikaCat** [comment]
@mohammedpatla I am using `go version go1.17 darwin/amd64` on my mac. I tested you repo on the fresh server and I still can't reproduce the error. Yes, running it in the docker would be good option, have you tried it yet?

**Comment by Nick011** [comment]
I'm also attempting to fork for Secret.

I'm receiving the following error:

```
bdjuno/config on  v2/cosmos/stargate [?] on ☁️  us-east-2 took 10s
❯ bdjuno parse-genesis --home ~/.bdjuno
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x143a5f2]

goroutine 1 [running]:
github.com/forbole/juno/v2/node/remote.NewNode(0xc0004e86a0, {0x1c90038, 0xc0004e89d0})
        /home/nick/go/pkg/mod/github.com/forbole/juno/v2@v2.0.0-20211221121955-cf2fcf04394b/node/remote/node.go:41 +0x32
github.com/forbole/juno/v2/node/builder.BuildNode({{0xc000049540, 0x506}, {0x1c2c420, 0xc0004e86a0}}, 0x6)
        /home/nick/go/pkg/mod/github.com/forbole/juno/v2@v2.0.0-20211221121955-cf2fcf04394b/node/builder/builder.go:17 +0xbe
github.com/forbole/juno/v2/cmd/parse.GetParsingContext(0xc000599300)
        /home/nick/go/pkg/mod/github.com/forbole/juno/v2@v2.0.0-20211221121955-cf2fcf04394b/cmd/parse/setup.go:41 +0x386
github.com/forbole/bdjuno/v2/cmd/parse-genesis.NewParseGenesisCmd.func1(0xc0004dd680, {0xc0004c4220, 0x0, 0x2})
        /home/nick/Documents/work/whispernode/bdjuno/cmd/parse-genesis/parseGenesis.go:21 +0x3f
github.com/spf13/cobra.(*Command).execute(0xc0004dd680, {0xc0004c4200, 0x2, 0x2})
        /home/nick/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001fcf00)
        /home/nick/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /home/nick/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/tendermint/tendermint/libs/cli.Executor.Execute({0xc0001fcf00, 0x1a70010})
        /home/nick/go/pkg/mod/github.com/forbole/tendermint@v0.34.13-0.20210820072129-a2a4af55563d/libs/cli/setup.go:89 +0x4a
main.main()
        /home/nick/Documents/work/whispernode/bdjuno/cmd/bdjuno/main.go:43 +0x2ca
```

My `~/.bdjuno/config.toml`
```
chain:
  bech32_prefix: secret
  modules:
    - modules
    - messages
    - auth
    - gov
    - staking
node:
  type: remote
config:
  rpc:
    client_name: pulsar
    address: http://xxxx:26657
    max_connections: 20
  grpc:
    address: http://xxx:9090
    insecure: true
parsing:
  workers: 1
  listen_new_blocks: true
  parse_old_blocks: true
  parse_genesis: false
  start_height: 1
  fast_sync: true
  genesis_file_path: /home/nick/Documents/work/whispernode/bdjuno/config/genesis.json
database:
  name: dipper
  host: big-dipper.xxxxxx.us-east-2.rds.amazonaws.com
  port: 5432
  user: postgres
  password: "xxxxxxxxx"
  schema: public
  max_open_connections: 10
  max_idle_connections: 10
logging:
  level: debug
  format: text
telemetry:
  port: 5000
pruning:
  keep_recent: 100
  keep_every: 500
  interval: 10
pricefeed:
    tokens:
        - name: secret
          units:
            - denom: uscrt
              exponent: 0
            - denom: scrt
              exponent: 6
              price_id: secret
distribution:
  rewards_frequency: 100
```

The error appears to be pointing:
- [here](https://github.com/forbole/juno/blob/v2/cosmos-stargate/node/remote/node.go#L41-L44)
- This appears to be an error thrown from the rpc client `jsonrpcclient.DefaultHTTPClient` (which I haven't fully explored yet)
- I am able to `curl` the rpc endpoint defined in the config 
    - `curl xxxx:26657/status`
    -
     ``` 
      ❯ curl xxxxx:26657/status
  {
    "jsonrpc": "2.0",
    "id": -1,
    "result": {
      "node_info": {
        "protocol_version": {
          "p2p": "8",
          "block": "11",
          "app": "0"
        },
        "id": "xxxxxxxxxxx",
        "listen_addr": "tcp://0.0.0.0:26656",
        "network": "secret-4",
        "version": "0.34.14",
        "channels": "40202122233038606100",
        "moniker": "whispernode",
        "other": {
          "tx_index": "on",
          "rpc_address": "tcp://0.0.0.0:26657"
        }
      }
      ... etc
    ```
