### ISSUE TITLE
Research: Optimization Testing

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#284]
# IS IT GRPC?! IS IT PSQL?!
What if it's neither...

## Synopsis
In the past few months we have bought this issue up multiple times and each time we have failed to come to any factual conclusion or make any huge improvement.

This issue would like to request some engineers from the bdjuno team to do a series of tests using some of the optimization ideas below. This will allow us to compare to the current bdjuno and figure out where the bottleneck issue could be located.

### Test 1 (Kwun)
If it is a postgres issue we can easily test this by seeing if we are able to insert faster (and accurately) into psql without any unique keys in the initial parsing stage.

### Test 2 (Riccardo)
Reading data from the DB directly instead of relying on gRPC/RPC. It requires the node to be stopped though (not running)

**Comment by huichiaotsou** [comment]
result : https://enchanting-duck-6fa.notion.site/Performance-Test-b9a9a50b1577419189d288833157d98b
