### ISSUE TITLE
Txs Aggregation timeout for chains with huge amounts of data

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#289]
This is specifically for Terra, Band and Solana (handled by SolJuno)

Currently the query below will always hang and never return due to the default behavior of psql (It will go through the table and count in real time).

```
query Transactions($limit: Int = 7, $offset: Int = 0) {
  transactions: transaction(limit: $limit, offset: $offset, order_by: {height: desc}) {
    height
    hash
    success
    block {
      timestamp
    }
    messages
    logs
  }
  total: transaction_aggregate {
    aggregate {
      count
    }
  }
}
```

Removing the following will return the data right away

```
  total: transaction_aggregate {
    aggregate {
      count
    }
  }
```

I will see if i can do a workaround on the frontend in the meantime but I believe this is something that can be better handled at the back

**Comment by rmontagnin** [comment]
Have you tried using two different queries instead? The count should not be a problem at all since PostreSQL runs that in O(1)

**Comment by ryuash** [comment]
Yes I've tried separating the queries but it feels like the bottleneck is the count aggregation as it returns right away without it.

The following query took about 1 minute for Band to return any response and about 3 minutes in Solana. 
```
query Transactions {
  total: transaction_aggregate {
    aggregate {
      count
    }
  }
}
```
Not sure if this is expected but is there a way to improve the performance?

There's no way O(1) takes this long. It feels like O(n)...

**Comment by rmontagnin** [comment]
After reading [this StackExchange conversation](https://dba.stackexchange.com/questions/245990/postgresql-extremely-slow-count-with-index-simple-query) it appears to be a PostgreSQL related problem. Apparently to count all rows of a table PostgreSQL iterates over all of them. To fix this I've run the following commands: 
```
vacuum analyze transaction;
ALTER TABLE transaction SET (
  autovacuum_vacuum_scale_factor = 0,
  autovacuum_analyze_scale_factor = 0,
  autovacuum_vacuum_threshold = 10000,
  autovacuum_analyze_threshold = 10000
);
```
This will set the vacuum function of PostgreSQL to run more frequently which will allow a faster iteration over all the records.
