### ISSUE TITLE
Get proposals tally result

### ISSUE THREAD

**Issue by RiccardoM** [forbole/bdjuno#29]
## Feature description 
After implementing #28, we need to get each proposal tally result. As far as I've understood, tally results represent the current proposal status. This means that if it's in `DepositPeriod`, it represents the total amount of tokens deposited. Otherwise, if it's in the `VotingPeriod` it represents the different votes that have been casted. 

## Implementation proposal
To implement this, I would suggest we store in two different tables each deposit made and each vote casted for a proposal. Such data can be get handling properly the `MsgDeposit` and `MsgVote` messages respectively. 

These data should be later sufficient to properly display anything the explorer might want to display.

**Comment by HarleyAppleChoi** [comment]
Do we interest to save like which voter voted over time?
For like handling msgVote we can save the action like the voter votes for what, and also the tally pool after the vote.

**Comment by RiccardoM** [comment]
@HarleyAppleChoi I think we should better save the single votes as well as you've proposed
