### ISSUE TITLE
Storing the change of validator information

### ISSUE THREAD

**Issue by kwunyeung** [forbole/bdjuno#3]
For the validator list and validator detail page, we will only show the latest information of a validator. 

https://xd.adobe.com/view/53042c53-f384-451e-7cee-e0da21dabd79-2535/screen/b69298e1-3197-4d89-ba85-ffe0d214abda/2-2-validator-details

### Validator detail
However, when a validator updates its validator detail and commission rate, the old values will be removed. I would like to let the users see the changes of the validator. Especially when a validator change its commission rate. 

This can only be done when parsing the `cosmos-sdk/MsgEditValidator` message. When the parser see this message, it has to store the original value of the validator and the changes it has done. The simplest way would be to link the original value with the corresponding edit validator tx.

### Validator uptime
The validator uptime is calculated by the amount of signatures the validator should have voted in the `signed block window`. The parameters can be retrieved from this endpoint.

```
http://lcd.cosmoshub.bigdipper.live/slashing/parameters
```
Here are the current slashing parameters

```json
{"height":"2225861","result":{
  "max_evidence_age": "1814400000000000",
  "signed_blocks_window": "10000",
  "min_signed_per_window": "0.050000000000000000",
  "downtime_jail_duration": "600000000000",
  "slash_fraction_double_sign": "0.050000000000000000",
  "slash_fraction_downtime": "0.000100000000000000"
}}
```
The validator signing information can be retrieved with the following (undocumented) endpoint.

```
http://lcd.cosmoshub.bigdipper.live/slashing/validators/{validator_consensus_pubkey)/signing_info
```
For example, to get the signing information of **Forbole**, you can query

```
http://lcd.cosmoshub.bigdipper.live/slashing/validators/cosmosvalconspub1zcjduepqmfxl36td7rcdzszzrk6c7kzp5l3jlw4lnxz8zms3py7qcsa9xlns7zxfd6/signing_info
```
and the result will be like this.

```json
{"height":"2225917","result":{
  "address": "",
  "start_height": "0",
  "index_offset": "5627914",
  "jailed_until": "1970-01-01T00:00:00Z",
  "tombstoned": false,
  "missed_blocks_counter": "0"
}}
```

The validator uptime can be calculated as

```
uptime = ( signed_blocks_window - missed_blocks_counter ) / signed_blocks_window * 100%
```

**Comment by RiccardoM** [comment]
With 62ceffe I've implemented an operation that every 15 secs stores of both the `signed_blocks_window` as well as the `missed_blocs_counter` values for all validators.

I think it's best to store the entire values themselves instead of the already computed `uptime` value. This way you can also have a more accurate information about the overall missed blocks counter values over time.

**Comment by HarleyAppleChoi** [comment]
Do you mean you finish storing staking?
So what I will do is set the command and functions that retrieve the info of the validator within the period?

**Comment by HarleyAppleChoi** [comment]
Or just uptime?

**Comment by RiccardoM** [comment]
@HarleyAppleChoi Please take care of the first point mentioned by @kwunyeung: 

> ## Validator detail
> However, when a validator updates its validator detail and commission rate, the old values will be removed. I would like to let the users see the changes of the validator. Especially when a validator change its commission rate.
> 
> This can only be done when parsing the cosmos-sdk/MsgEditValidator message. When the parser see this message, it has to store the original value of the validator and the changes it has done. The simplest way would be to link the original value with the corresponding edit validator tx.

In order to do so, what you can do is the following. 

First, define a message handler inside the `x/staking/module.go` file. A message handler is just a function (named as you wish that accepts a transaction, an index and a message parameters): 

```golang
import (
	"fmt"

	"github.com/cosmos/cosmos-sdk/codec"
	sdk "github.com/cosmos/cosmos-sdk/types"
	"github.com/cosmos/cosmos-sdk/x/staking"
	"github.com/desmos-labs/juno/parse/worker"
	"github.com/desmos-labs/juno/types"
)

func MsgHandler(tx types.Tx, index int, msg sdk.Msg, w worker.Worker) error {
	return nil
}
```

Then, inside such function the first things should be done: 

1. Make sure the message was sent successfully. 
2. Handle the message properly. 

This can be done with the following code: 

```golang
log.Info().Str("tx_hash", tx.TxHash).Int("msg_index", index).Str("msg_type", msg.Type()).Msg("found message")

if len(tx.Logs) == 0 {
	log.Info().Msg(fmt.Sprintf("Skipping message at index %d of tx hash %s as it was not successull",
		index, tx.TxHash))
	return nil
}


switch stakingMsg := msg.(type) {
case staking.MsgEditValidator:
	// TODO: Handle message here
	break
}

return nil
```

Finally, just handle the cast message inside the `swtich` case as it has been requested by Kwun.

**Comment by HarleyAppleChoi** [comment]
I don't quite sure about the implementation in modules.go and main.go

in modules.go-
`
func MsgHandler(tx types.Tx, index int, msg sdk.Msg, w worker.Worker) error {
	log.Info().Str("tx_hash", tx.TxHash).Int("msg_index", index).Str("msg_type", msg.Type()).Msg("found message")

	if len(tx.Logs) == 0 {
		log.Info().Msg(fmt.Sprintf("Skipping message at index %d of tx hash %s as it was not successull",
			index, tx.TxHash))
		return nil
	}

	switch stakingMsg := msg.(type) {
	case staking.MsgEditValidator:
		// TODO: Handle message here
		//store commission rate
		utils.WatchMethod(func() error { return StoreModifiedVaildator(stakingMsg,db) })
		}
	}

	return nil
}
`
How do I pass the database into the StoreModifiedVaildator, which is StoreModifiedVaildator(msg staking.MsgEditValidator,db database.BigDipperDb){
?

**Comment by RiccardoM** [comment]
@HarleyAppleChoi You can get the database by using this piece of code: 

```golang
db, ok := w.Db.(database.BigDipperDb)
if !ok {
	return fmt.Errorf("invalid database")
}
```
