### ISSUE TITLE
Missing transaction

### ISSUE THREAD

**Issue by kwunyeung** [forbole/bdjuno#305]
The following transaction is missing in the database

https://explorer.desmos.network/transactions/07173B40FD752753DEA247BDBD808A1B01B1638A4B44378B0B5649632CF452CD

and hence affecting the data consistency on the UI.

**Comment by MonikaCat** [comment]
The transaction was missing because the node we were using was sometimes unresponsive, I have applied the block fix and this tx is now stored in db.
