### ISSUE TITLE
Wrong proposal status on LikeCoin

### ISSUE THREAD

**Issue by kwunyeung** [forbole/bdjuno#307]
Proposal 30 and 31 are in voting period but showing `invalid` on Big Dipper https://likecoin.bigdipper.live/proposals

**Comment by huichiaotsou** [comment]
Checked with Hiep, not sure if it's that the bdjuno is pointing to a node with only 100 latest heights? 

ran fix cmd on the node that has historical data but returned  below errors:
```
$ bdjuno fix gov proposal 30
ERROR: error while handling MsgDeposit: error while getting proposal deposit: 
rpc error: code = InvalidArgument desc = rpc error: 
code = InvalidArgument desc = depositer: cosmos1h77f2qdx9hhq8ax94pvv5syn4c5tqkp6nldccp 
not found for proposal: 30: invalid request

$ bdjuno fix gov proposal 31
ERROR: error while handling MsgDeposit: error while getting proposal deposit: 
rpc error: code = InvalidArgument desc = rpc error: 
code = InvalidArgument desc = depositer: cosmos1lge9wv5p6d7nw75es6gpdgt6g4m2gjerz48k0w 
not found for proposal: 31: invalid request
```

HOWEVER, the below 2 cmds both returned data without errors:  
$ liked q gov deposit 31 cosmos1lge9wv5p6d7nw75es6gpdgt6g4m2gjerz48k0w
$ liked q gov deposit 30 cosmos1h77f2qdx9hhq8ax94pvv5syn4c5tqkp6nldccp

Gimme still a while to find out why 😭

**Comment by MonikaCat** [comment]
@huichiaotsou I fixed the status of proposal 30 and 31. There was a problem with a node as it was missing some of the blocks info and there was a lot of connections errors, so as a result bdjuno couldn’t parse the data correctly. I have pointed now bdjuno to another node and I am running fix to sync old blocks as there’s quite a few them missing in database

**Comment by huichiaotsou** [comment]
thanks @MonikaCat ! I forgot to look back on this issue LOL I will close it now.
