### ISSUE TITLE
[Akash] Implement provider status

### ISSUE THREAD

**Issue by APPLECHOI** [forbole/bdjuno#313]
## Feature description 
In order to help developers to choose a provider when hosting on Akash, we can show a list of providers and their stats on bd.

## Implementation proposal
We can query [Provider](https://github.com/ovrclk/akash/blob/26ba6825886c2720052fdee1908e25481cbc94cc/proto/akash/provider/v1beta2/query.proto#L14) from the chain. And it return owner, host_uti,attributes,info and jwt_host_uri.

**Comment by APPLECHOI** [comment]
I guess listening to 
 MsgCreateDeployment,
  MsgCloseDeployment,
  MsgCreateLease,
  MsgCloseLease,
  MsgCreateBid,
  MsgCloseBid,
  MsgDepositDeployment,
  MsgWithdrawLease
  would help with understanding provider status

**Comment by APPLECHOI** [comment]
Like from the provider we can already query region and provider that the region and stuff by MsgUpdateProvider
```
[
  {
    "@type": "/akash.provider.v1beta1.MsgUpdateProvider",
    "owner": "akash1aud9xcdvtxhreuuprxd0u55p9emsze8ajvggwf",
    "host_uri": "https://provider.chainzeroprovider.link:8443",
    "attributes": [
      {
        "key": "region",
        "value": "us-west"
      },
      {
        "key": "host",
        "value": "akash"
      },
      {
        "key": "tier",
        "value": "community"
      },
      {
        "key": "organization",
        "value": "chainzeroprovider"
      }
    ],
    "info": {
      "email": "",
      "website": ""
    },
    "address": null
  }
]
```

**Comment by rmontagnin** [comment]
@huichiaotsou Can this be closed now?
