### ISSUE TITLE
MsgCreatePeriodicVestingAccount not handled properly

### ISSUE THREAD

**Issue by kwunyeung** [forbole/bdjuno#315]
The following is a tx with `MsgCreatePeriodicVestingAccount`. The transfer recipient become a `PerodicVestingAccount` but it show being indexed.

https://agoric.bigdipper.live/transactions/05FA8772BBB192F684B6FBD67C1607C3E37B0BFEF2FF11D44BCFDCE045810DD4

**Comment by ryuash** [comment]
@huichiaotsou can this be closed?

**Comment by MonikaCat** [comment]
Closed with #318
