### ISSUE TITLE
Ability to run bdjuno without GRPC url

### ISSUE THREAD

**Issue by npow** [forbole/bdjuno#319]
## Feature description 
Many cosmos projects do not have publicly available GRPC endpoints (from what I see on [cosmos/chain-registry](https://github.com/cosmos/chain-registry)). It would be super useful to be able to run `bdjuno` with only an RPC endpoint configured. Is there a technical reason why this cannot be done?

**Comment by rmontagnin** [comment]
Some data cannot be fetched from the RPC, but are only available using either the REST APIs (aka LCD) or the gRPC endpoints. This is the case for things that are updated every block and are stored within the chain state such as delegation rewards. For this reason, we cannot only rely on the RPC to run BDJuno.
