### ISSUE TITLE
Does BDJuno support ethermint based chains (not just Evmos)?

### ISSUE THREAD

**Issue by justindotpub** [forbole/bdjuno#320]
Forgive me for asking a question as an issue but I wasn't sure where else to ask.  I see in #179 that Ethermint is supported but I assume that was Evmos before it was renamed (as evidenced by that branch no longer existing but the evmos branch existing).  Are ethermint based chains supported as well?  My guess was that they might be supported as long as I use a recent enough version of ethermint with the appropriate IBC code.

Thank you for work and time.  🙏🏻

**Comment by rmontagnin** [comment]
Ethermint (now EVMOS) is supported because it's a Cosmos-based chain. BDJuno only supports those chains that are based on the [Cosmos SDK](https://github.com/cosmos/cosmos-sdk). All other chains are **not** supported by this parser.

**Comment by justindotpub** [comment]
Thanks for the reply @RiccardoM.

Just so I'm super clear, my question was not about BDJuno working with the Evmos chain (that used to also be called Ethermint) but about BDJuno working with other custom chains that might be built from Ethermint the library (which is still called Ethermint and is used by the Evmos chain).

If I'm hearing you correctly, you're saying that as long as said chains are based on the Cosmos SDK they should be supported.  Do you by chance have a minimum version of Cosmos SDK required for support?

Thank you.

**Comment by rmontagnin** [comment]
> If I'm hearing you correctly, you're saying that as long as said chains are based on the Cosmos SDK they should be supported. 

That's correct

Do you by chance have a minimum version of Cosmos SDK required for support?

We have two branches: `v2/cosmos/stargate` for Stargate-based Cosmos chains, and `v2/cosmos/v0.44.x` for Cosmos `v0.43.x` and above.

**Comment by justindotpub** [comment]
Thank you. 🙏🏻

That answers my questions.  👍🏻
