### ISSUE TITLE
Query token prices of IBC tokens

### ISSUE THREAD

**Issue by kwunyeung** [forbole/bdjuno#324]
Currently the total value of an account can't be calculated as the token price of the IBC tokens are not considered.

To solve this, the only way we can do now is to hard-code the IBC tokens denom details and query from coingecko of all those tokens. This will not be efficient if we have to do this to all BDJuno on different chains. Should we create microservice serving IBC token details among Interchain? This should also serve https://github.com/forbole/big-dipper-2.0-cosmos/issues/684

**Comment by rmontagnin** [comment]
Done inside [IBCJuno](https://github.com/forbole/ibcjuno).
