### ISSUE TITLE
[hasura actions] turn all the response coin type to string? 

### ISSUE THREAD

**Issue by huichiaotsou** [forbole/bdjuno#325]
## Feature description 

Given that sifchain is 18 exponents, it's easy to encounter "range exceeds int64" while implementing hasura actions. I then aborted sdk.Coin as response type and created custom type of Coin for actions with turning the Amount field into string which solves the issue.

Should we turn the amount field to string for all the coin responses ?

**Comment by ryuash** [comment]
@MonikaCat We need this for Evmos
