### ISSUE TITLE
Unable to add custom types

### ISSUE THREAD

**Issue by justyntemme** [forbole/bdjuno#344]
I am trying to fork BDJUNO for use with the github.com/pylons-tech blockchain. I have copied over the 
`starport generate proto-go` types from the pylons repository into the root types folder. When i run `bdjuno parse` with the RPC set to `rpc.testnet.pylons.tech` I receive this error when parsing

 ```re-enqueueing failed block err="failed to handle transaction with hash 7E08FB93713AD62FE0801BD1D8E12CF8FBB476DF9302C35E4094C03835A7B8E8: unable to resolve type URL /Pylonstech.pylons.pylons.MsgCreateCookbook" height=1170```

I have put a breakpoint on the init() function of the generated pb file, which i can confirm is hit. I also can confirm the type is registered with the correct URL that's stated in the error message. The specific register line is hit with the proper URL, confirmed via breakpoints.

I believe this is causing the issue of incomplete data in the postgres database, which leads to no data being shown on the bdjuno frontend react app.

**Comment by rmontagnin** [comment]
That's a classic message which is shown when you haven't properly setup BDJuno to work with custom messages. Did you follow [this guide](https://docs.bigdipper.live/cosmos-based/parser/custom-chains) to setup BDJuno for your chain?

**Comment by justyntemme** [comment]
I have read that, however after re-reading it seems we are not including our app module manager. Thank you for the help will close now.
