### ISSUE TITLE
Enable Token Price History without History Module

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#348]
Issue:
Currently token price history is only enabled if `history` module is enabled.

There will be networks that don't require history and I would like to retrieve their token price history in order to display a 7 day chart.

Implementation:
Separate Token Price History from history. Log the price once a day (seriously once a day should be enough)

**Comment by huichiaotsou** [comment]
@ryuash currently there's only storing price in history module, can we say we just remove history module and store the price history every 30 secs as usual?

**Comment by ryuash** [comment]
Every 30 seconds is a bit extreme for ui's use-case. 
I just want the price once a day but I would have to search through 2880 rows for each day. 2880 * 7 just to get 7 days of price history.

I don't mind logging them all back in to `token_price` table please also check with X on this as they switched to `token_price_history`

edit:
Also okay with hourly and i can display the 24 hours change

**Comment by MonikaCat** [comment]
I think we can add it to the `pricefeed` module to query the price once a day and store it inside new `daily_token_price_history` table. This way we keep history module optional to enable for users.

**Comment by ryuash** [comment]
Can we default this to hourly instead?

Both BD and X does not need it every 30 seconds - 2 minutes and just logging once per hour is more than enough. I've confirmed with @calvinkei 

Implementation 
- Add a frequency config specifically for tokens that defaults to every hour
- Enable this by default in `token` module **or** create a `token_history` module
- Keep the data in `token_price_history` table

I don't see any usecase for such high frequency as we are not coin gecko and I don't see the point of creating a new table as it's still considered history.
