### ISSUE TITLE
v2.0.0 uses cosmos sdk version v0.42.9 breaking compatibility 

### ISSUE THREAD

**Issue by justyntemme** [forbole/bdjuno#357]
In go.mod for the v2.0.0 release, the cosmos sdk is set to v0.42.9, which breaks compatibility with modules that are based on .44.x. If you upgrade the module a bunch of stuff breaks in the repository and no longer builds correctly

## Steps to reproduce
 

clone the repo and make no changes except adding an App module based on .44.x cosmos. When running go mod tidy you will get this output 
`go get: upgraded github.com/cosmos/cosmos-sdk v0.42.9 => v0.44.5`

This will cause a breakage in the repo and i am unable to compile.

## Expected behavior

I expect to be able to add my module and use the .44.x cosmos-sdk definitions.

**Comment by rmontagnin** [comment]
Thanks for the report. I've just noticed I tagged the wrong commit. Let me tag v2.0.1 and delete v2.0.0 tomorrow

**Comment by rmontagnin** [comment]
@justyntemme Just released `v2.0.1`. Tomorrow I will delete `v2.0.0` tags

**Comment by justyntemme** [comment]
Awesome, I appreciate your quick reply, was solved before i got back from lunch. Thank you!

**Comment by justyntemme** [comment]
@RiccardoM  Ope it looks like the go.mod still uses the replace line 
`replace github.com/cosmos/cosmos-sdk => github.com/desmos-labs/cosmos-sdk v0.43.0-alpha1.0.20211102084520-683147efd235`

Which causes an issue with duplicate warning errors, can we remove this alltogether?

**Comment by rmontagnin** [comment]
@justyntemme Just pushed `v2.0.2` which replaces `v2.0.0` and `v2.0.1`

**Comment by justyntemme** [comment]
Compiles successfully, seeing other issues but not related to this one. Thanks again for your hard work and quick replies!
