### ISSUE TITLE
Duplicate Error registration

### ISSUE THREAD

**Issue by justyntemme** [forbole/bdjuno#361]
## Bug description
After adding a custom module manager `pylons.ModuleBasics`, i get a runtime error regarding duplicate error registeration.

```Exception has occurred: panic
"error with code 2 is already registered: \"invalid proof\""
Stack:
```

I was hopeful you could tell me where Bdjuno calls the cosmos/types/errors registration function, so that i could ensure pylons app module is not also calling the error registration.

**Comment by huichiaotsou** [comment]
Hi @justyntemme could you pls show me the complete error message and the repository of `pylons` & of your `bdjuno fork`? It's probably an issue regarding the inconsistent dependency version.

**Comment by justyntemme** [comment]
Hi there, i think we have solved the inconsistent vendoring, but i will be sure to double check. As of right now i am using only forboles repository, making one small change to add the pylons.AppModule{}. 

When i follow the steps outlined in the docs, it upgrades the deps to .44.5 instead of .44.4, but i don't think that is an issue. Here is the output
```
╰─⠠⠵ go get -u github.com/Pylons-tech/pylons 
go get: added github.com/Pylons-tech/pylons v0.4.1
go get: upgraded github.com/cosmos/cosmos-sdk v0.44.4 => v0.44.5
go get: upgraded github.com/cosmos/iavl v0.17.2 => v0.17.3
```

Complete Error message
```
Exception has occurred: panic
"error with code 2 is already registered: \"invalid proof\""
Stack:
	 2  0x00000000014b6f3e in github.com/cosmos/cosmos-sdk/types/errors.Register
	     at [c:/go/pkg/mod/github.com/cosmos/cosmos-sdk]()@v0.44.5/types/errors/errors.go:163
	 3  0x000000000263fe3f in github.com/cosmos/ibc-go/v2/modules/core/23-commitment/types.init
	     at [c:/go/pkg/mod/github.com/cosmos/ibc-go/v2]()@v2.0.0/modules/core/23-commitment/types/errors.go:12
	     

```
  I have a hunch it has to do with ibc/2 however i believe we have all of our references updated, i will check to be certain.

**Comment by justyntemme** [comment]
I think i found it, it seems juno/v2 imports `github.com/cosmos/cosmos-sdk v0.42.9` It seems that Bdjuno imports juno/v2 and not the updated juno/v3. As we are using cosmos .44.x we need to update the bdjuno imports to call juno/v3

**Comment by MonikaCat** [comment]
Hey @justyntemme thanks for reporting that. We will update ibc-go package to higher version, in the meantime you can try updating juno version inside go.mod file to `v2.0.1-0.20220303154752-50c37a0f96e7`

**Comment by justyntemme** [comment]
It looks like when that is done, we are now both importing ibc-go/v2 and ibc-go/v3, leading us to the same error.

Is there currently a branch that has ibc-go v2, but uses cosmos .44.x on everything else, including the juno references? That may work best for us.
Here is the go.mod after running `go mod tidy` after changing the /juno/v2 reference to v2.0.1-0.20220303154752-50c37a0f96e7


```
	github.com/cosmos/ibc-go/v2 v2.0.0 // indirect
	github.com/cosmos/ibc-go/v3 v3.0.0-rc0 // indirect
```

**Comment by justyntemme** [comment]
Here is the call stack for the error.
![Capture](https://user-images.githubusercontent.com/7116592/158212170-7d1489e2-6106-4e79-84bb-a963a0c7412f.PNG)

**Comment by MonikaCat** [comment]
Are you registering `gaiaapp` inside`main.go`? Try to replace it with `simapp` instead

**Comment by justyntemme** [comment]
I am only registering `pylonsapp.appModule` and have replaced both simapp, and the new gaiaapp line. I will take a look for some more vendoring issues as i have found before, is there a need for juno/v3 instead of the v2?

**Comment by huichiaotsou** [comment]
@justyntemme you may try the juno version `v2.0.0-20220308070656-570bc10bf70a` in which ibc-go is updated to `v2`. The `ibc-go` package should also be `v2` in the `gaia app` dependency so I would suggest you use `v6.0.4`:

```golang
require (
    github.com/cosmos/gaia/v6 v6.0.4
    github.com/forbole/juno/v2 v2.0.0-20220308070656-570bc10bf70a
)
```

Let me know whether this helps.

**Comment by justyntemme** [comment]
Did not see this message from you, will try today and repeat back TY :D

**Comment by justyntemme** [comment]
I'm happy to report that fixed our issue, tysm this has been a huge pain for us. Will be VERY excited to issue a PR for a pylons branch of bdjuno 🥳
