### ISSUE TITLE
[Bitsong] - Bdjuno unables to parse the tx type /cosmos.authz.v1beta1.MsgGrant. 

### ISSUE THREAD

**Issue by maiquanghiep** [forbole/bdjuno#362]
Bdjuno is running fine on Bitsong but some of the transactions can't be parsed. 
`Mar 13 23:10:13 bitsong-m-bdjuno-ln-atl bdjuno[764061]: 11:10PM ERR re-enqueueing failed block err="failed to get transactions for block: error while unpacking message: no concrete type registered for type URL /cosmos.authz.v1beta1.MsgGrant against interface *types.Msg" height=5050773`

**Comment by huichiaotsou** [comment]
bitsong upgraded to sdk v0.44.5, updated bdjuno branch updated and deployed at the server.
