### ISSUE TITLE
 Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by motiio** [forbole/bdjuno#393]
After "bdjuno start" command, the process crashes with an error

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x14da658]

goroutine 1 [running]:
github.com/forbole/bdjuno/v3/modules/actions.NewModule({{0xc000158e00, 0x375, 0x376}, {{0xc000e0af98, 0x7}, {0xc000da6d20, 0x5, 0x5}}, {{0xc000e0b040, 0x6}, ...}, ...}, ...)
	/root/bdjuno/modules/actions/module.go:41 +0x98
github.com/forbole/bdjuno/v3/modules.(*Registrar).BuildModules(_, {{{0xc000158e00, 0x375, 0x376}, {{0xc000e0af98, 0x7}, {0xc000da6d20, 0x5, 0x5}}, {{0xc000e0b040, ...}, ...}, ...}, ...})
	/root/bdjuno/modules/registrar.go:74 +0xf8
github.com/forbole/juno/v3/cmd/parse/types.GetParserContext({{0xc000158e00, 0x375, 0x376}, {{0xc000e0af98, 0x7}, {0xc000da6d20, 0x5, 0x5}}, {{0xc000e0b040, 0x6}, ...}, ...}, ...)
	/root/go/bin/pkg/mod/github.com/forbole/juno/v3@v3.1.1/cmd/parse/types/setup.go:57 +0x7d8
github.com/forbole/juno/v3/cmd/start.NewStartCmd.func1(0xc000e6c000?, {0x2a435b0?, 0x0?, 0x0?})
	/root/go/bin/pkg/mod/github.com/forbole/juno/v3@v3.1.1/cmd/start/cmd.go:37 +0x5c
github.com/spf13/cobra.(*Command).execute(0xc000e6c000, {0x2a435b0, 0x0, 0x0})
	/root/go/bin/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000ddb400)
	/root/go/bin/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/bin/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/tendermint/tendermint/libs/cli.Executor.Execute({0xc000ddb400?, 0x1b92b08?})
	/root/go/bin/pkg/mod/github.com/forbole/tendermint@v0.34.13-0.20210820072129-a2a4af55563d/libs/cli/setup.go:89 +0x4a
main.main()
	/root/bdjuno/cmd/bdjuno/main.go:47 +0x30a

**Comment by MonikaCat** [comment]
Hi @motiio can you share your config.yaml file and tell me which bdjuno branch you are currently using? Also please provide me with the rpc/grpc endpoint being used so I can investigate, thanks

**Comment by motiio** [comment]
Hi! Hi! Hi!)

It is my config file:
![Screenshot 2022-04-19 at 17 37 35](https://user-images.githubusercontent.com/60034446/164029622-aef354c3-0d0e-490b-b95d-cd293e735ba6.png)

I used the "cosmos/v0.44.x"

https://rpc.torii-1.archway.tech/

Thanks for your help

P.s This error appears even if I use the "bdjuno parse genesis-file" command

**Comment by effofxprime** [comment]
When I received these errors, it had something to do with the config.yaml file.
I suggest renaming it, and then trying to rerun `bdjuno init` and try with the barebones of what it has.  Edit what needs to be edited but don't add extra.

**Comment by huichiaotsou** [comment]
Hi @motiio @effofxprime, the hasura actions port is not set in your `config.yaml` file, please refer to the doc [config reference of actions](https://docs.bigdipper.live/cosmos-based/parser/config/config#actions) for the example of setting up hasura actions.

**Comment by huichiaotsou** [comment]
hi @motiio @effofxprime did above setting solve the issue? a concrete example here: 

```yaml
actions:
    port: 3000
```

Please reopen the issue if you have further questions.
