### ISSUE TITLE
ERR re-enqueueing failed block

### ISSUE THREAD

**Issue by Dark345** [forbole/bdjuno#397]
## Bug description

Just set up a bdjuno istance for agoric-3 chain. bdjuno is reporting:

`ERR re-enqueueing failed block err="failed to get block results from node: RPC error -32603 - Internal error: could not find results for height #4633760" height=4633760`

It basically repeats for every block, but randomly it's fetching them correctly

```
Apr 22 22:57:43 myhost bdjuno[942]: 10:57PM DBG processing block height=4633755
Apr 22 22:57:47 myhost bdjuno[942]: 10:57PM DBG enqueueing new block height=4633756
Apr 22 22:57:47 myhost bdjuno[942]: 10:57PM DBG processing block height=4633756
Apr 22 22:57:52 myhost bdjuno[942]: 10:57PM DBG enqueueing new block height=4633757
Apr 22 22:57:52 myhost bdjuno[942]: 10:57PM DBG processing block height=4633757
Apr 22 22:57:57 myhost bdjuno[942]: 10:57PM DBG enqueueing new block height=4633758
Apr 22 22:57:57 myhost bdjuno[942]: 10:57PM DBG processing block height=4633758
Apr 22 22:58:02 myhost bdjuno[942]: 10:58PM DBG enqueueing new block height=4633759
Apr 22 22:58:02 myhost bdjuno[942]: 10:58PM DBG processing block height=4633759
Apr 22 22:58:02 myhost bdjuno[942]: 10:58PM ERR re-enqueueing failed block err="failed to get block results from node: RPC error -32603 - Internal error: could not find results for height #4633759" height=4633759
```
and it starts again

at the same time, agoric node signals this

`ERR error while stopping connection error="already stopped" module=rpc-server protocol=websocket`

## Steps to reproduce
 

It starts almost istantly after firing up bdjuno

## Expected behavior

no error

**Comment by rmontagnin** [comment]
@Dark345 This is actually fine, you shouldn't have any problem due to it
