### ISSUE TITLE
[Sifchain] Unable to parse new types URL

### ISSUE THREAD

**Issue by maiquanghiep** [forbole/bdjuno#398]
Sifchain had an upgrade last week. Bdjuno currently can't handle this types URL 

- `/sifnode.clp.v1.MsgUnlockLiquidityRequest`
- `/sifnode.clp.v1.MsgAddRewardPeriodRequest`
- `/sifnode.clp.v1.MsgUpdatePmtpParams`
- `/sifnode.clp.v1.MsgAddRewardPeriodRequest`
- `/sifnode.clp.v1.MsgUpdateRewardsParamsRequest`

**Comment by huichiaotsou** [comment]
fixed with [d3162d05121f](https://github.com/forbole/bdjuno/commit/d3162d05121f06b9e9a6f70e990946dd9d492bb1)
