### ISSUE TITLE
Consensus module is not updating

### ISSUE THREAD

**Issue by HarleyAppleChoi** [forbole/bdjuno#40]
There is only one row on consensus table and it never updates.
    ```
     "height": 1761,
        "round": 0,
        "step": "RoundStepPrevote"
```

**Comment by RiccardoM** [comment]
@HarleyAppleChoi Have you tried subscribing to that table using GraphQL subscriptions? The `consensus` module is different from the other ones in a manner that it uses a single line. That lines gets constantly and very fast updated. Checking it every 5/10 seconds, the height should be the most visible change

**Comment by HarleyAppleChoi** [comment]
@RiccardoM No, I don't see any changes😢

**Comment by RiccardoM** [comment]
@HarleyAppleChoi I think this bug was due to Cosmos not being updated. I have tried running the code inside the `riccardo/cosmos-update` branch (the one used in #45), and everything works. If you want to try it, here's the GraphQL subscription to use: 

```
subscription Consensus {
  consensus {
    height
    round
    step
  }
}
```

**Comment by HarleyAppleChoi** [comment]
Yeah that is working now
