### ISSUE TITLE
Osmosis branch (origin/monika/osmosis) missing SQL function self_delegations?

### ISSUE THREAD

**Issue by jotham** [forbole/bdjuno#405]
## Bug description
Checking out branch `origin/monika/osmosis` shows that there is expected to be a SQL function called `self_delegations` in database/schema/03-staking.sql which is now missing?

It's unclear to me if this is an oversight, or something is out of date on this branch, as I can't see `self_delegations` in the main codebase anymore.

It's unclear to me what revision of bdjuno I should be using for osmosis testnet.

This looks like the since deleted function:

schema/03-staking.sql-/**
schema/03-staking.sql:  * This function is used to add a self_delegations field to the validator table allowing to easily get all the
schema/03-staking.sql-  * self delegations related to a specific validator.
schema/03-staking.sql- */
schema/03-staking.sql:CREATE FUNCTION self_delegations(validator_row validator) RETURNS SETOF delegation AS
schema/03-staking.sql-$$
schema/03-staking.sql-SELECT *
schema/03-staking.sql-FROM delegation
schema/03-staking.sql-WHERE delegator_address = (
schema/03-staking.sql-    SELECT self_delegate_address
schema/03-staking.sql-    FROM validator_info
schema/03-staking.sql-    WHERE validator_info.consensus_address = validator_row.consensus_address
schema/03-staking.sql-)
schema/03-staking.sql-$$
schema/03-staking.sql-    LANGUAGE sql
schema/03-staking.sql-    STABLE;
schema/03-staking.sql-

## Steps to reproduce

1. Clone bdjuno repository
2. `git checkout origin/monika/osmosis`
3. Import all `database/schema/*.sql` files
4. Apply hasura metadata in `hasura/`

## Expected behavior
Expect the metadata to import successfully.  Instead it complains:
`
Inconsistent object: in table "validator": in computed field "self_delegations": no such function exists: "self_delegations"
`

**Comment by rmontagnin** [comment]
Please note from the name that this is a testing branch that should not be used by anyone except the author. It's most likely out of date or something else needs to be done to make it work. Closing this as it's not an issue with an official branch
