### ISSUE TITLE
Save HEX pubkey as well as the pubkey for each validator

### ISSUE THREAD

**Issue by HarleyAppleChoi** [forbole/bdjuno#41]
## Feature description 
Saving HEX pubkey into database so that we do not need to calculate that everytime we want to get HEX from pubkey
## Implementation proposal
When adding a validator we can map to a HEX pubkey as well.

**Comment by kwunyeung** [comment]
@RiccardoM @bragaz do you know if there are methods in the SDK which convert the validator `bech32` pubkey back the `Tendermint` validator hex address? We need this in `BDJuno` to map the signatures in the block.

**Comment by RiccardoM** [comment]
@kwunyeung If you have the public key, you can use the `.Address()` method that's inside the `PubKey` interface.

**Comment by kwunyeung** [comment]
@RiccardoM it's to record if the validator's precommit signature exists in the current block. For example, http://lcd.morpheus.desmos.network:1317/blocks/5000 the signatures are referencing the validators in `hex` address but what we can get from validator list are the addresses in `bech32`. We should save the hex address along with the validator information.

**Comment by RiccardoM** [comment]
@kwunyeung I guess that can be done easily by changing how Juno saves the data, adding the HEX address and pub key to the validator table

**Comment by HarleyAppleChoi** [comment]
@RiccardoM Yes, please take care of that inside Juno, feeling that is better than doing it in BDJuno🧐

**Comment by RiccardoM** [comment]
Move to desmos-labs/juno#4
