### ISSUE TITLE
Allow manual trigger of interval tasks

### ISSUE THREAD

**Issue by ivan-ngchakming** [forbole/bdjuno#415]
## Feature description 

Was running BDjuno but it hasn't been a day yet, I want to manually trigger the calculate inflation function but can't seem to be able to find a way to do it. Perhaps BDjuno can allow user trigger interval tasks manually, so they can be triggered on demand, I feel this would be especially useful during development.

Especially tasks that runs less frequently than hourly, like inflation and community pool:
https://github.com/forbole/bdjuno/blob/cosmos/v0.44.x/Requirements.md#on-intervals

## Implementation proposal

Add new commands to CLI so users can trigger interval tasks manually.

Would love to help with implementing this if you think this is worth implementing.

**Comment by rmontagnin** [comment]
This seems like an interesting an useful feature to me. Would you please open a PR for it?
