### ISSUE TITLE
ValidatorDelegations not loading 

### ISSUE THREAD

**Issue by devashar13** [forbole/bdjuno#470]
## Bug description

On opening the bigdipper website I saw that validator delegations were not loading, so I checked the network tab and saw that the response for the specific query had timed out . 

## Steps to reproduce
 
The bug can be clearly seen in the website for example check page (https://cosmos.bigdipper.live/validators/cosmosvaloper1udpsgkgyutgsglauk9vk9rs03a3skc62gup9ny) in the delegations tab

When I run the graphql query on my local instance on bdjuno I get the response 
<img width="962" alt="image" src="https://user-images.githubusercontent.com/51401092/191998175-01b628cf-56a6-46fb-941e-82162f2d709c.png">

## Expected behavior

The query should respond with the validator's delegation addresses and amounts

**Comment by devashar13** [comment]
Was looking into this a little more, realised this is only a problem with cosmos , rest of the chains are working perfectly

**Comment by huichiaotsou** [comment]
After testing it's because of the `count-total` is making this query time-out. It should be fixed somehow on the frontend to disable count-total and implement another way for displaying next pages. 
ref.  forbole/big-dipper-2.0-cosmos#1010
