### ISSUE TITLE
unable to resolve type URL /ethermint.crypto.v1.ethsecp256k1.PubKey

### ISSUE THREAD

**Issue by spac3unit** [forbole/bdjuno#479]
Hello!
I'm trying to index Haqq chain (https://github.com/haqq-network/haqq/)

I'm add chain according to the docs, and successfully make install. Everything works fine, blocks indexing, but for some blocks i got error:
`ERR re-enqueueing failed block err="error while storing txs: failed to handle transaction with hash DAC66C2971B97E81BB61BB332E88B2C96AD4063DDFBD2E06B8A826385089F532: unable to resolve type URL /ethermint.crypto.v1.ethsecp256k1.PubKey" height=520868`

This is how this tx looks in the correct working explorer:
https://haqq.explorers.guru/transaction/DAC66C2971B97E81BB61BB332E88B2C96AD4063DDFBD2E06B8A826385089F532

Any ideas how to fix?
Thx!

**Comment by rmontagnin** [comment]
@spac3unit Did you correctly setup BDJuno instance as written [here](https://docs.bigdipper.live/cosmos-based/parser/custom-chains)?

**Comment by spac3unit** [comment]
@RiccardoM Hello man.
I hope so :) This is what i did:
1. go get -u github.com/haqq-network/haqq@v1.2.0
2. add replacements from haqq [go.mod](https://github.com/haqq-network/haqq/blob/master/go.mod#L165)
3. in cmd/bdjuno/main.go i add:
`haqqapp "github.com/haqq-network/haqq/app"` to the import section
and `haqqapp.ModuleBasics`  to the end of return statement in func getBasicManagers()
4. make install

The problem is that transactions with message type "MsgWithdrawDelegatorReward" and "MsgWithdrawValidatorCommission" (default cosmos-sdk distribution module) are not saved in the database. Only transactions of type "ethermint.evm.v1.MsgEthereumTx" are saved.
Only the information about the transactions themselves is not saved. Information about the block and the number of transactions in it is saved

**Comment by huichiaotsou** [comment]
hey @spac3unit do you have a clone repo of bdjuno where I can check your modification? It would be great if you could provide me with the rpc/grpc endpoints of your chain so I can test on my end. Cheers.

**Comment by spac3unit** [comment]
@huichiaotsou Hello. Sorry for delay.
repo: https://github.com/spac3unit/haqq-juno-test
rpc: http://185.16.38.136:26660
grpc: http://185.16.38.136:9093

**Comment by huichiaotsou** [comment]
Hi @spac3unit, it seems like a codec issue. You may try the below. 

In `types/config/encoding.go`, import:
```go
import evmenc "github.com/evmos/ethermint/encoding"
```

and update the method `MakeEncodingConfig()` as below
```go
// MakeEncodingConfig creates an EncodingConfig to properly handle all the messages
func MakeEncodingConfig(managers []module.BasicManager) func() params.EncodingConfig {
	return func() params.EncodingConfig {
		manager := mergeBasicManagers(managers)
		encodingConfig := evmenc.MakeConfig(manager)
		return encodingConfig
	}
}
```

Please let me know if this does not work.
