### ISSUE TITLE
Hasura metadata applied but tables not created

### ISSUE THREAD

**Issue by piotr-sikora-v** [forbole/bdjuno#496]
I have running hasura in docker with postgres:12
I added `HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres` to docker-compose environment, and in Hasura conosle is state connected.

but when I apply data, then is inconsistent ... looks like there is no created tables in hasura postgres related to `HASURA_GRAPHQL_DATABASE_URL` 

Also, when I go to Hasura console I can create table, and then it exist in my docker postgres... also error with inconsistent for this table dismiss.

I do everything in https://docs.bigdipper.live/cosmos-based/parser/hasura/
What I missed?

**Comment by huichiaotsou** [comment]
@piotr-sikora-v 
could you explain more about `tables not created`? Have you created the bdjuno database and the tables before launching hasura container?

**Comment by piotr-sikora-v** [comment]
@huichiaotsou ah... so it's must be connected with same database that are bdjuno is connected... ok.
I miss understad that. 
Thanks!

**Comment by Maksat-luci** [comment]
> @huichiaotsou ah... so it's must be connected with same database that are bdjuno is connected... ok. I miss understad that. Thanks!

really? hasura should be connected to the database that bdjuno is connected to? if so, how did you do it, could you show the docker-compose file hasuru, it's just that I also tried to connect to my postgres that is connected to bdjuno, and then hasura did not work at all
