### ISSUE TITLE
Track chain average block times

### ISSUE THREAD

**Issue by RiccardoM** [forbole/bdjuno#50]
As discussed inside desmos-labs/juno#5, particularly [here](https://github.com/desmos-labs/juno/issues/5#issuecomment-688674413), we should track how average block time changes over time. 

For this reason, we should create three different tables: 

```sql
CREATE TABLE average_block_time_per_minute 
(
  average_time DECIMAL NOT NULL, 
  timestamp TIMESTAMP WITHOUT TIMEZONE NOT NULL
);

CREATE TABLE average_block_time_per_hour
(
  average_time DECIMAL NOT NULL, 
  timestamp TIMESTAMP WITHOUT TIMEZONE NOT NULL
);

CREATE TABLE average_block_time_per_day
(
  average_time DECIMAL NOT NULL, 
  timestamp TIMESTAMP WITHOUT TIMEZONE NOT NULL
);
```

Each of these tables should be updated *every time a new block is created*. Particularly, here are how values should be computed. 

#### `average_block_time_per_minute`
`average_time = (BlockTime - PreviousMinuteBlockTime) / (BlockHeight - PreviousMinuteBlockHeight)` 

####  `average_block_time_per_hour`
`average_time = (BlockTime - PreviousHourBlockTime) / (BlockHeight - PreviousHourBlockHeight)` 

#### `average_block_time_per_day`
`average_time` = (BlockTime - YesterdayBlockTime) / (BlockHeight - YesterdayLastBlockHeight)

--- 

@kwunyeung can you please confirm this is correct?

**Comment by HarleyAppleChoi** [comment]
@RiccardoM Good. And then it would be like:
1. Periodic operation on x/consensus?
2. Take the old value from database
3. Calculate block time
4. Put it into database
Is that?

**Comment by RiccardoM** [comment]
@HarleyAppleChoi Yes, having a block operation inside `x/consensus` seems the best thing to do. The steps you described are correct :100:

**Comment by kwunyeung** [comment]
@RiccardoM the calculation is correct but only the overall average block time has to be calculated on every block, which 

```
average_time = (BlockTime - GenesisTime) / BlockHeight
```

And I suppose the other average block times can be done on every min, every hour and every day instead of on every new block. In the current version, we have a timer dispatch a function every second. If the current time is at 0 second of every min, 0 second of every hour and 00:00 of every day, it will make those calculations.

**Comment by RiccardoM** [comment]
@kwunyeung Great, thanks! 

@HarleyAppleChoi Please implement the calculations as periodic operations then. Leave only the overall average one (the one against the genesis time) inside the block handler.
