### ISSUE TITLE
1-to-n relationships are used instead of 1-1

### ISSUE THREAD

**Issue by RiccardoM** [forbole/bdjuno#58]
## Bug description
Currently inside the GraphQL data definitions, there are some places in which 1-to-n relationships are used instead of 1-to-1. For example, this is the case in the following query used when retrieving all validators' identities.

Currently it is:

```gql
query Validator {
  validator{
    validator_infos {
      validator_descriptions {
        identity
      }
    }
  }
}
```

The returned value is: 

```json
{
  "validator": [
    {
      "validator_infos": [
        {
          "validator_descriptions": [
            {
              "identity": ""
            },
            {
              "identity": "51468B615127273A"
            }
          ]
        }
      ]
    }
  ]
}
```

Instead, the query should be 

```gql
query Validator {
  validator {
    validator_description {
      identity
    }
  }
}
```

And the returned value should be

```json
{
  "validator": [
    {
      "validator_description": {
        "identity": "51468B615127273A"
      }
    }
  ]
}
```

The relationships 
- `validator` -> `validator_info` 
- `validator_info` -> `validator_description` 

Should both be 1-to-1 instead of 1-to-n.

We need to check those relationships to make sure they are initialized as 1-to-1 instead of 1-to-n. Also, a check should be made on all other relationships as well.

**Comment by rmontagnin** [comment]
Closed with b28222b60a1d75a7e7411b4dab9264f323d453d5
