### ISSUE TITLE
Desmos Big Dipper Interface Query Questions

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#59]
Is https://m1k.gql.morpheus.desmos.network/console still the correct api?

Just to give me a kickstart can you provide me with the follow queries while I slowly figure out the schema?

<details>
<summary>Latest Height</summary>
<img width="258" alt="Screen Shot 2020-11-23 at 1 47 04 PM" src="https://user-images.githubusercontent.com/42913823/99932283-8e408400-2d92-11eb-961e-8df416a37cb5.png">
</details>

<details>
<summary>Validators</summary>
<img width="253" alt="Screen Shot 2020-11-23 at 1 47 39 PM" src="https://user-images.githubusercontent.com/42913823/99932767-09ef0080-2d94-11eb-9a75-7b8ef14ef581.png">
</details>

<details>
<summary>Stabilities (ignore this one if the comment below is still valid)</summary>
<img width="250" alt="Screen Shot 2020-11-23 at 1 47 45 PM" src="https://user-images.githubusercontent.com/42913823/99932807-2428de80-2d94-11eb-9400-262c40efa425.png">
</details>

<details>
<summary>Consensus</summary>
<img width="257" alt="Screen Shot 2020-11-23 at 1 47 49 PM" src="https://user-images.githubusercontent.com/42913823/99932886-605c3f00-2d94-11eb-9fc4-bb9a045c8cb4.png">
</details>

---

<details>
<summary>Previous Edit (Reference Purposes)</summary>
## Average Block Time [OK]
<img width="256" alt="Screen Shot 2020-11-23 at 1 47 32 PM" src="https://user-images.githubusercontent.com/42913823/99932514-3f471e80-2d93-11eb-97b1-b5919a1ed5b9.png">

```
/**
 * Get the average block time from genesis
 */
export const AVERAGE_BLOCK_TIME_FROM_GENESIS_QUERY = gql`
query AverageBlockTimeAllTime{
  average_block_time_from_genesis(limit: 1, order_by: {height: desc}){
    average_time
  }
}`;

/**
 * Get the average block time by last minute
 */
export const AVERAGE_BLOCK_LAST_MINUTE_QUERY = gql`
query AverageBlockTimeLastMinute{
  average_block_time_per_minute(limit: 1, order_by: {height: desc}){
    average_time
  }
}`;

/**
 * Get the average block time by last hour
 */
export const AVERAGE_BLOCK_LAST_HOUR_QUERY = gql`
query AverageBlockTimeLastHour{
  average_block_time_per_hour(limit: 1, order_by: {height: desc}){
    average_time
  }
}`;

/**
 * Get the average block time by last 24 hours
 */
export const AVERAGE_BLOCK_LAST_DAY_QUERY = gql`
query AverageBlockTimeLastDay{
  average_block_time_per_day(limit: 1, order_by: {height: desc}){
    average_time
  }
}`;
```

## Price [OK] - I currently hardcoded 0 since this is a testnet
<img width="256" alt="Screen Shot 2020-11-23 at 1 47 36 PM" src="https://user-images.githubusercontent.com/42913823/99932714-e2983380-2d93-11eb-87e1-cb28145f9cf7.png">

```
export const PRICE = gql`
  subscription price{
    token_price(limit: 1, order_by: {timestamp: desc}) {
    price
    market_cap
    denom
    }
}`;
```

## Stabilities
<img width="250" alt="Screen Shot 2020-11-23 at 1 47 45 PM" src="https://user-images.githubusercontent.com/42913823/99932807-2428de80-2d94-11eb-9400-262c40efa425.png">

I don't think this is the correct query

```
query community_pool {
  community_pool(limit: 1, order_by: {height: desc}) {
   coins
 }
}
```

## Consensus
<img width="257" alt="Screen Shot 2020-11-23 at 1 47 49 PM" src="https://user-images.githubusercontent.com/42913823/99932886-605c3f00-2d94-11eb-9fc4-bb9a045c8cb4.png">

I have the following query below but it returns an empty array at the moment. Not sure if this available for testnet
```
query consensus_state{
    consensus{
      height
      round
      step
    }
  }
```

## Latest Blocks
<img width="503" alt="Screen Shot 2020-11-23 at 1 47 54 PM" src="https://user-images.githubusercontent.com/42913823/99933074-eaa4a300-2d94-11eb-9648-178c7252bb41.png">

The following query does not give me info about the proposer itself. I need the identity and moniker of the proposer not the validators

```
/**
 * Get the latest blocks with pagination
 * @param limit limits the amount of data coming back
 * @param offset offset
 */
export const LATEST_BLOCKS_QUERY = gql`
query LatestBlocks($limit: Int!, $offset: Int!) {
  block(limit: $limit, order_by: {height: desc}, offset: $offset) {
    hash
    proposer {
      validator_infos {
        validator_descriptions(order_by: {timestamp: desc}) {
          moniker
          operator_address
        }
      }
    }
    height
    num_txs
    timestamp
  }
}`;
```

## Latest Activities

<img width="502" alt="Screen Shot 2020-11-23 at 1 47 59 PM" src="https://user-images.githubusercontent.com/42913823/99933086-f1cbb100-2d94-11eb-8e75-ad916071fe13.png">

Is there a way to filter by message.type?

```
query LatestActivies {
  transaction(order_by: {timestamp: desc}, where: {messages: {_is_null: false}}, limit: 10) {
    messages
  }
}
```

</details>

**Comment by RiccardoM** [comment]
#### Stabilities
In order to get the data related to this component, the following queries should be used:

```gql
subscription Stabilities{
  pool:staking_pool (order_by:{height: desc}, limit:1){
    bonded_tokens
    not_bonded_tokens
  }
  total_tokens: supply(order_by: {height: desc}, limit: 1){
    coins
  }
  community_pool: community_pool(order_by:{height: desc}, limit:1) {
    coins
  }
  inflation:inflation(order_by:{height:desc}, limit:1){
    value
  }
}
```

I guess that `market_cap = price * total_tokens`.

#### About inflation
Inflation is a property of the `minting` module, which might not be enabled for everyone. As an example, Desmos does not have this enabled. In this case, the inflation should be considered to be `0%` (no new tokens are minted on a regular base).

**Comment by rmontagnin** [comment]
@ryuash Here are the queries:
<details> 

<summary>Latest height</summary>

```graphql
subscription LatestHeight {
  latest_height: block(order_by: {height: desc}, limit: 1) {
    height
    timestamp
  }
}
```

</details>

<details> 

<summary>Validators</summary>

```graphql
query Validators {
  active_validators: validator_aggregate(where: {validator_status: {status: {_eq: 2}}}) {
    aggregate {
      count
    }
  }
  not_active_validators: validator_aggregate(where: {validator_status: {status: {_neq: 2}}}) {
    aggregate {
      count
    }
  }
}
```

</details>


<details>

<summary>Stabilities</summary>

See [the above comment](https://github.com/forbole/bdjuno/issues/59#issuecomment-734145081)

</details>

<details> 

<summary>Consensus state</summary>

```graphql
subscription Proposer {
  proposer: block(order_by: {height: desc}, limit: 1) {
    height
    validator {
      consensus_address
      validator_description {
        moniker
      }
    }
  }
}

subscription Consensus {
  consensus {
    height
    step
  }
}
```

**Note**. The consensus right now is not working.

</details>

**Comment by ryuash** [comment]
Our current `not_active` count is 0 (for the moment) but i noticed some validator description/status are null. Shouldn't they have counted towards `not_active`? And are they null due to the current node still syncing?

```
{
  "validator_info": {
    "self_delegate_address": "desmos1qdsansn5se37wy80zr2upc8y6klv35u8643x8j",
    "operator_address": "desmosvaloper1qdsansn5se37wy80zr2upc8y6klv35u8ycejdq"
  },
  "validator_description": null,
  "validator_status": null
}
```

Asking as the ui requires info on `not_active` validators

![image](https://user-images.githubusercontent.com/42913823/104144873-fd843d00-53ff-11eb-9e37-88df88944ad2.png)
![image](https://user-images.githubusercontent.com/42913823/104144893-0c6aef80-5400-11eb-981e-4584578e5196.png)

**Comment by rmontagnin** [comment]
> Our current `not_active` count is 0 (for the moment) but i noticed some validator description/status are null. Shouldn't they have counted towards `not_active`? And are they null due to the current node still syncing?
> 
> ```
> {
>   "validator_info": {
>     "self_delegate_address": "desmos1qdsansn5se37wy80zr2upc8y6klv35u8643x8j",
>     "operator_address": "desmosvaloper1qdsansn5se37wy80zr2upc8y6klv35u8ycejdq"
>   },
>   "validator_description": null,
>   "validator_status": null
> }
> ```
> 
> Asking as the ui requires info on `not_active` validators

Most likely yes, those are null because BDJuno is still parsing the data.
