### ISSUE TITLE
Daily delegations and unbonding data

### ISSUE THREAD

**Issue by kwunyeung** [forbole/bdjuno#6]
We would like to show the daily delegation and unbonding amount. This can be done by querying all the delegations and unbonding information from all validators. It will be interesting when comparing the delegations with token price.

**Comment by RiccardoM** [comment]
Would you like to have a per-account base delegation/undelegation tracking, or more something a global tracking?

**Comment by RiccardoM** [comment]
After yesterday's call, we've decided to track on a per-account base. 

That being said, the following API endpoints can be used to query the data:

- `/staking/validators/{validatorAddr}/delegations`
- `/staking/validators/{validatorAddr}/unbonding_delegations`

This should allow us to save both for validators as well for delegators.
