### ISSUE TITLE
BeginBlocker/EndBlocker events

### ISSUE THREAD

**Issue by IDerr** [forbole/bdjuno#605]
Does BDjuno indexes events from the BeginBlocker and EndBlocker?

It could be interesting to have that if some chains use these mechanisms to make some computations

Thanks for your work

**Comment by rmontagnin** [comment]
We, BDJuno does support handling BeginBlocker and EndBlocker events. However by default it does not index them. You need to fork the codebase and update it to store them by creting a custom module that implements `BlockModule` which has a functon named `HandleBlock` that is given also the block-related events (both begin and end ones)

**Comment by IDerr** [comment]
Well noted, will try that! thanks for the answer
