### ISSUE TITLE
How to add customize cosmos app chain into the bdjuno?

### ISSUE THREAD

**Issue by VegeBun-csj** [forbole/bdjuno#619]
we have setup an app chain, how can we add it into bdjuno?

**Comment by MonikaCat** [comment]
Hi @VegeBun-csj to learn how to setup BDJuno for your custom chain follow our docs here https://docs.bigdipper.live/

**Comment by VegeBun-csj** [comment]
@MonikaCat hi, can u help add our app chain into the bdjuno? we have encounterd some issue.

**Comment by VegeBun-csj** [comment]
@MonikaCat hi, bro. We have encountered an issue:
![img_v2_d402771b-f02a-4ead-8895-96f508be09ah](https://github.com/forbole/bdjuno/assets/39252213/8d8ce5e5-984c-46c6-a0c1-ecec11f1527b)
I researched the bdjuno source code and found the error comes from the lib [juno](https://github.com/forbole/juno/blob/c75730cef0854cf1795bb76fd16ff62388743bab/parser/worker.go#L71). How can we solve it?
Also i found many branched in juno repositry, Do we need to push a customize juno branch?

**Comment by zura35** [comment]
Hi @VegeBun-csj as the error suggested, it seems like the grpc server on your end might be unable to serve the request made by client in bdjuno. Can you check if you have registered the Tx service on your grpc server correctly? Thanks!

**Comment by VegeBun-csj** [comment]
@zura35 hey bro. Thank you for your suggestion. I have solved the problem, and i meet a new problem:
<img width="1461" alt="image" src="https://github.com/forbole/bdjuno/assets/39252213/21cd3806-df38-43af-a2ce-7b45fa0b0d2c">

**Comment by zura35** [comment]
Hi @VegeBun-csj may I ask if you have already added the module according to this [tutorial](https://docs.bigdipper.live/cosmos-based/parser/custom-chains#add-your-application-modules) before starting bdjuno? 🙏

**Comment by VegeBun-csj** [comment]
> Hi @VegeBun-csj may I ask if you have already added the module according to this [tutorial](https://docs.bigdipper.live/cosmos-based/parser/custom-chains#add-your-application-modules) before starting bdjuno? 🙏

@zura35  yeah, i have added the [application modules](https://docs.bigdipper.live/cosmos-based/parser/custom-chains/#add-your-application-modules) into my bdjuno main.go, and i compiled it successfully. Also im using it to start.
<img width="662" alt="image" src="https://github.com/forbole/bdjuno/assets/39252213/dff42316-5825-420b-a47f-fcfa345b8d08">

I noticed that i didnt add [custom addresses parser](https://docs.bigdipper.live/cosmos-based/parser/custom-chains/#optional-add-your-custom-addresses-parser) into the bdjuno, Maybe it cause the problem?

**Comment by VegeBun-csj** [comment]
@zura35 I have resolved it with changeing the wasm version! :) thanks bro
