### ISSUE TITLE
i have error parsing my transaction throw bdjuno 

### ISSUE THREAD

**Issue by mousaibrah** [forbole/bdjuno#651]
I have this error after I tried to run $ bdjuno parse transaction all

although I put my module basic in the main file I still got this error 

feel free to check our chain [ggezchain](https://github.com/GGEZLabs/ggezchain)

Thanks for all your time, sorry for any inconvenience 

![Screenshot 2023-09-19 102727](https://github.com/forbole/bdjuno/assets/121259768/3e8b488b-bf0e-4c92-b91a-116c44de70f1)

**Comment by zura35** [comment]
Hi @mousaibrah may I ask if you have already followed the instructions from [here](https://docs.bigdipper.live/cosmos-based/parser/custom-chains#add-your-application-modules)? 🙏

**Comment by mousaibrah** [comment]
> Hi @mousaibrah may I ask if you have already followed the instructions from [here](https://docs.bigdipper.live/cosmos-based/parser/custom-chains#add-your-application-modules)? 🙏

```js

func getBasicManagers() []module.BasicManager {
    return []module.BasicManager{
        simapp.ModuleBasics,
        ggezchain.ModuleBasics
            
    }
}
```

I added this line but I don't think I need address parser 
I already use my modules in react using  [Telescope](https://github.com/cosmology-tech/telescope) and everything run smoothly but I need to read the transaction from big-dipper explorer 
please let me know if I need to implement anything else in bdjuno 

Thank you @zura35  for your time .

**Comment by zura35** [comment]
Hi @mousaibrah This is a bit difficult to look into the issue without the source codes, would you be able to show us your fork?

**Comment by mousaibrah** [comment]
Hi @zura35   sure  here is the repo for bdjuno [ Code](https://github.com/mousaibrah/bdjuno) and if you need the source code for our chain app [Code](https://github.com/GGEZLabs/ggezchain)

**Comment by VegeBun-csj** [comment]
I also meet this error with https://github.com/forbole/bdjuno/issues/619, im using the [wasm module](https://github.com/CosmWasm/wasmd), and i add the module basics into bdjuno. Maybe the same problem

**Comment by mousaibrah** [comment]
> Hi @mousaibrah This is a bit difficult to look into the issue without the source codes, would you be able to show us your fork?
Hi @zura35  I hope you're doing well, Did you take any time to look into my conundrum? I'm stumped and don't know what to do.
Thank you Zura and sorry if I'm a bit hasty

**Comment by mousaibrah** [comment]
> Hi @mousaibrah This is a bit difficult to look into the issue without the source codes, would you be able to show us your fork?

Hi @zura35  I hope you're doing well, Did you take any time to look into my conundrum? I'm stumped and don't know what to do.
Thank you Zura and sorry if I'm a bit hasty

**Comment by zura35** [comment]
Hi @mousaibrah I haven't found the cause yet, I have tried to do the followings:
1. clone your ggezchain repo and serve in dev mode via `ignite chain serve`
1. clone your bdjuno implementation and copy the genesis file created from ignite
1. update the config file to point to local rpc and grpc nodes
1. add a line to print `reg.ListImplementations("cosmos.base.v1beta1.Msg")` upon start cmd run
1. parse genesis and start bdjuno

I found that `/ggezchain.trade.MsgCreateTrade` is printed from the log I added 🤔 Wonder how I could simulate tx create-trade locally... On the other hand @MonikaCat wonder if you would have any idea to this issue? 🙏

**Comment by mousaibrah** [comment]
> Hi @mousaibrah I haven't found the cause yet, I have tried to do the followings:
> 
> 1. clone your ggezchain repo and serve in dev mode via `ignite chain serve`
> 2. clone your bdjuno implementation and copy the genesis file created from ignite
> 3. update the config file to point to local rpc and grpc nodes
> 4. add a line to print `reg.ListImplementations("cosmos.base.v1beta1.Msg")` upon start cmd run
> 5. parse genesis and start bdjuno
> 
> I found that `/ggezchain.trade.MsgCreateTrade` is printed from the log I added 🤔 Wonder how I could simulate tx create-trade locally... On the other hand @MonikaCat wonder if you would have any idea to this issue? 🙏

Thanks for taking the time and trying to fix my issue.

you can create trade by the following :

1. Copy and update the file [chain_acl.json](https://github.com/GGEZLabs/ggezchain/blob/main/chain_acl.json) into .ggezchain and update the mutaz and mohd address
2. then add this command to your terminal and update the receiver address and signer address
```js
ggezchaind tx trade create-trade buy uggez 0.01 15000 $mohd '{"TradeData":{"tradeRequestID":123,"assetHolderID":456,"assetID":789,"tradeType":"Buy","tradeValue":100.50,"currency":"USD","exchange":"NYSE","fundName":"Tech Fund","issuer":"Company A","noShares":"1000","price":"50.25","quantity":"10","segment":"Technology","sharePrice":"49.50","ticker":"TECH","tradeFee":"5.00","tradeNetPrice":"500.00","tradeNetValue":"495.00"},"Brokerage":{"name":"XYZ Brokerage","type":"Online","country":"USA"}}' --from $mutaz
```
then you can see the height and see that bdjuno stops at this same height and returns this error 

ERROR: Error while re-fetching transactions of height 387652: failed to get transactions for block: error while unpacking message: no concrete type registered for type URL /ggezchain.trade.MsgCreateTrade against interface *types.Msg


I hope that help you figure out my issue, Thanks again for you time

**Comment by zura35** [comment]
@mousaibrah Thanks for the detailed instructions, I managed to fetch the transaction without error 🤔 
<img width="1363" alt="Screenshot 2023-09-25 at 4 59 40 PM" src="https://github.com/forbole/bdjuno/assets/53038542/c0e17523-5c33-4702-a80b-cda35abcf1b1">

Could you try to clean your go mod cache to refetch packages from your chain for bdjuno, and rebuild the binary?

**Comment by mousaibrah** [comment]
> @mousaibrah Thanks for the detailed instructions, I managed to fetch the transaction without error 🤔 <img alt="Screenshot 2023-09-25 at 4 59 40 PM" width="1363" src="https://user-images.githubusercontent.com/53038542/270286437-c0e17523-5c33-4702-a80b-cda35abcf1b1.png">
> 
> Could you try to clean your go mod cache to refetch packages from your chain for bdjuno, and rebuild the binary?


I'm really sorry Zura is there a way that you can give me instructions on how you did it because I've tried to clear my go cache
and the bdjuno cache and make build for both apps and reset for the chain and truncate for the tables 
and still got nowhere so I'll be very grateful if you have just a little bit more time to tell me how :)

**Comment by zura35** [comment]
@mousaibrah fyi
```bash
> ignite version
Ignite CLI version:		v0.27.1-dev
Ignite CLI build date:		2023-06-13T13:42:09Z
Ignite CLI source hash:		4acd1f185afb6d8d1a837e54f04c091121cfae01
Ignite CLI config version:	v1
Cosmos SDK version:		v0.47.3
Your OS:			darwin
Your arch:			arm64
Your Node.js version:		v20.5.1
Your go version:		go version go1.21.0 darwin/arm64

mousaibrah__bdjuno % > git status
On branch main
Your branch is up to date with 'origin/main'.

```

Other than the log lines I have added, there are two things I have done mainly (but the first one is prolly unrelated):
1. I updated the docker compose file to spin up postgres instead of installing locally
2. I copied the `database` folder from `forbole/bdjuno` repo branch `cosmos/v0.47.x` to your bdjuno implementation as it is missing

Then I run the database migration as usual and start bdjuno just as described in https://github.com/forbole/bdjuno/issues/651#issuecomment-1733093570

**Comment by mousaibrah** [comment]
Thank you  for all your help sorry for any inconvenience @zura35  🌹🌹
