### ISSUE TITLE
Online voting power average by day

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#69]
## Feature description 

Currently there is no efficient way for the frontend of big dipper to calculate the average online voting power by day without some performance costing calculation.

![image](https://user-images.githubusercontent.com/42913823/103983958-3aaebc00-51c1-11eb-9040-b6fbae0b9364.png)

## Implementation proposal

Make an aggregation what will allow big dipper to input a start and end date (if end date is null return only start date) and return the average of each day.

notes: or i can pass 2021-01-03T00:00:00Z to 2021-01-03T11:59:59Z. Whichever works better

ex: 
*start_date* : 2021-01-03T00:00:00Z
*end_date* : 2021-01-06T00:00:00Z

return
```
[
    {
        date: '2021-01-03T00:00:00Z',
        average_voting_power: 1200,
    },
    {
        date: '2021-01-04T00:00:00Z',
        average_voting_power: 1200,
    },
    {
        date: '2021-01-05T00:00:00Z',
        average_voting_power: 1200,
    },
    {
        date: '2021-01-06T00:00:00Z',
        average_voting_power: 1200,
    }
]
```

**Comment by rmontagnin** [comment]
@ryuash I've updated BDJuno and the GraphQL endpoint and now you can get such data using the following query: 

```graphql
query VotingPower($start: timestamp, $end: timestamp) {
  block(where: {timestamp: {_gte: $start, _lte: $end}, validator_voting_power_histories: {}}) {
    voting_power_history: validator_voting_power_histories_aggregate {
      aggregate {
        sum {
          voting_power
        }
      }
    }
  }
}
```

Please note that the `$start` and `$end` value should be provided through a single JSON object formed as follow: 
```json
{
  "start": "2020-10-10T19:07:30.000000",
  "end":"2020-10-10T19:08:32.99999"
}
```

Both should be timestamps in ISO 8601 format.

This will return the following response: 
```json
{
  "data": {
    "block": [
      {
        "voting_power_history": {
          "aggregate": {
            "sum": {
              "voting_power": 78650
            }
          }
        }
      }
    ]
  }
}
```

Each object inside the `block` array represents a single block and its complex `voting_power`. What you should do is get all the objects, and do an average of the `voting_power` values to get the average voting power across the time frame you provided.

**Note**. The above query returns the voting power of all the validators, even if they are unbonding. I don't know if we should filter all the ones that are jailed or not though

**Comment by ryuash** [comment]
I followed the query but i'm unable to fetch most durations is this expected?
ex: 
The following returns an empty array
```
query VotingPower {
  block(where: {timestamp: {_gte: "2020-10-01T00:00:00.000000", _lte: "2020-10-01T23:59:59.99999"}, validator_voting_power_histories: {}}) {
    voting_power_history: validator_voting_power_histories_aggregate {
      aggregate {
        sum {
          voting_power
        }
      }
    }
  }
}
```

but the following returns the expected

```
query VotingPower {
  block(where: {timestamp: {_gte: "2020-10-11T00:00:00.000000", _lte: "2020-10-11T23:59:59.99999"}, validator_voting_power_histories: {}}) {
    voting_power_history: validator_voting_power_histories_aggregate {
      aggregate {
        sum {
          voting_power
        }
      }
    }
  }
}
```

the difference is `2020-10-11` and `2020-10-01`

**Comment by rmontagnin** [comment]
@ryuash Yes, that is expected since the first blocks of the chain have been produced in `2020-10-06`. You can see this by running the following query:

```graphql
query Blocks {
  block(order_by:{height:asc}, limit: 2) {
    height
    timestamp
  }
}
```

Also, please note that currently not all blocks' voting power histories have been parsed properly so this might result in the missing of some data. This is due to the fact that this block's voting power history feature has been added after the start of the BDJuno and thus initial blocks might not have been parsed at all.
