### ISSUE TITLE
Account daily snapshot

### ISSUE THREAD

**Issue by kwunyeung** [forbole/bdjuno#7]
Is it even possible that we can have a daily account snapshot? I want eventually let users to see the daily change of the account. This affect to those accounts which has delegation as the reward (and commission for validators) keep changing on every block. We can't just rely on the transfer transactions to track the changes.

**Comment by RiccardoM** [comment]
I think this can be done easily. How often do you think will be a fair refresh rate? 15 seconds or less often?

**Comment by RiccardoM** [comment]
As discussed during the call of today, I will implement this by: 

1. Parsing `MsgSend` and `MsgMultiSend` messages in order to get new accounts as they are created. 
2. Querying the LCD daily to get the balances of the accounts themselves.
