### ISSUE TITLE
Return all validators involved in the tx

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#71]
## Feature description 

Let me know if this idea is even realistic.

Currently all messages returns a self delegate address for all parties involved. Because they are self delegates there is no sure way to know if the user is also a validator unless another query is called to check. Out of all the checks approximately only 30% or less will hold a validator identity.

```
{
    "timestamp": "2020-10-10T18:08:07",
    "hash": "87CFD8594E65ABFBA58F49B2D7F05C97C7C8A28B75D51CEBF53BB0D33D4274B0",
    "height": 67144,
    "memo": "Welcome, to the real world...😎",
    "messages": [
      {
        "type": "cosmos-sdk/MsgSend",
        "value": {
          "amount": [
            {
              "denom": "udaric",
              "amount": "10000000"
            }
          ],
          "to_address": "desmos168wz6xz6tnzvl2qwee264x0x9sr8yz0vtkp2cj",
          "from_address": "desmos1dzn2s7l0wm9kekyazcnhapu8j95n90efmcmrad"
        }
      }
    ]
  }
```
## Implementation proposal

Add an aggregation to return all validators involved in the transaction.

ex:
```
{
  ..tx stuff,
  validators: [
    identity
    moniker
    validator_address
  ]
}
```

**Comment by rmontagnin** [comment]
Since each message has its own structure, this is not possible. It would mean that we already know all the possible messages' structure and the fields that represent an account address, which is not possible since we are agnostic about the chain that is feeding us the data.
