### ISSUE TITLE
Add `is_self_delegated` to delegations

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#73]
## Feature description 

Be able to filter out self delegations within a group of delegations towards a single validator

## Implementation proposal

Add a `is_self_delegated` prop

```
delegation (where: {is_self_delegated: {_eq: true}}) {
  ...
}
```

**Comment by rmontagnin** [comment]
This can be achieved using [compute fields](https://hasura.io/docs/1.0/graphql/core/schema/computed-fields.html). I think we should add this to both `delegation` and `delegation_history` tables.

**Update**. 
Looks like computed fields are not supported inside filtering: hasura/graphql-engine#3772

**Comment by rmontagnin** [comment]
@ryuash I've solved this by adding the following: 

- a `is_self_delegate` field to the `delegation` table, which tells if a row represents a self delegation
- a `is_self_delegate` field to the `delegation_history` table, which tells if a row represents a self delegation
- a `self_delegations` field to the `validator` table, which returns only the self delegations that validator has
- a `self_delegation_histories` field to the `validator` table, which returns only the self delegation histories of that validator
