### ISSUE TITLE
v0.47 - Bad Power Voting % calculation

### ISSUE THREAD

**Issue by RaulBernal** [forbole/bdjuno#734]
## Bug description
% Voting power for validators is not being rightly calculated
<img width="1187" alt="image" src="https://github.com/forbole/callisto/assets/3751926/595cb563-04ea-4b2f-bcee-aaad76256d0b">

Running v0.47 branch, no errors running the binary (no weird logs)

## Steps to reproduce
https://explorer2.bitcanna.io/validators

## Expected behavior
Expected valid percentage range

**Comment by ghost** [comment]
I have checked code and there's a false index using in `for range`.

[This fix-up](https://github.com/Lorenzo-Protocol/callisto/pull/3/files) would solve the problem.

**Comment by RaulBernal** [comment]
> I have checked code and there's a false index using in `for range`.
> 
> [This fix-up](https://github.com/Lorenzo-Protocol/callisto/pull/3/files) would solve the problem.



> I have checked code and there's a false index using in `for range`.
> 
> [This fix-up](https://github.com/Lorenzo-Protocol/callisto/pull/3/files) would solve the problem.

Hello, fix-up applied, should I need to clean any table or so? Thanks 
Still showing the bad data:
https://explorer2.bitcanna.io/validators

**Comment by ghost** [comment]
Oh sorry, I mixed up your question with mine (I thought it was a total voting power problem).

I went to check Bitcanna's bonded tokens:
```
simd q staking pool --node https://bitcanna.rpc.nodeshub.online:443

bonded_tokens: "89,824,000,156,839"
not_bonded_tokens: "29,425,808,310,765"
```

The BigDipper shows the total voting power as `89,823,998`. Then it must be a problem in **unit conversion**.

Try to configure the token units part in `web/your-project/chain.json` as follows:
```json
{
  "primaryTokenUnit": "ubcna",
  "votingPowerTokenUnit": "ubcna",
  "tokenUnits": {
    "bcna": {
      "display": "ubcna",
      "exponent": 6
    }
  }
}
```

I'm not getting deep into its implementation, and [the doc](https://docs.bigdipper.live/cosmos-based/frontend/chain-config#token-units) confuses me as well, but this could solve your problem.

**Comment by RaulBernal** [comment]
Thanks @orisalden it works! 
That config was messed, the "bcna" was "ubcna" and the reverse inside "tokenUnits"; so that was the reason.

**Comment by RaulBernal** [comment]
Opps, it shows 105% of Voting (116 vals when it should show 100)
I have applied the previous fix and restarted but still.

**Comment by ghost** [comment]
> Opps, it shows 105% of Voting (116 vals when it should show 100) I have applied the previous fix and restarted but still.

Oh, you can check the `validator_voting_power` and `validator_status` tables in the PostgreSQL database. The UI relies on GraphQL queries to get the latest status. Do the tables have the correct count of active validators?

**Comment by RaulBernal** [comment]
> > Opps, it shows 105% of Voting (116 vals when it should show 100) I have applied the previous fix and restarted but still.
> 
> Oh, you can check the `validator_voting_power` and `validator_status` tables in the PostgreSQL database. The UI relies on GraphQL queries to get the latest status. Do the tables have the correct count of active validators?

Yeah, you are right, there are some validators not marked as "jailed". When I change the value in database ofc it reflects.

**Comment by RaulBernal** [comment]
`callisto parse staking  validators ` doesn't help

**Comment by RaulBernal** [comment]
Installing a new clean database/callisto
