### ISSUE TITLE
message_type table is empty

### ISSUE THREAD

**Issue by nezha90** [forbole/bdjuno#744]
## Bug description

I used "appd tx send * *" for the transfer operation, and I can see this message in the transaction data table, but it cannot be correctly written into the message table. He reported the following error. Does anyone have a solution

`Jun 06 16:37:35 node-2 callisto[421725]: 4:37PM ERR error while handling message err="pq: insert or update on table \"message_0\" violates foreign key constraint \"message_type_fkey\"" height=84083 module=mess>`

```
bdjuno=# select * from message_type;
 type | module | label | height
------+--------+-------+--------
(0 rows)
```

## Expected behavior

What is the role of the message_type table?

**Comment by nezha90** [comment]
I don't see handle_msg.go in "[modules/bank](https://github.com/nezha90/callisto/blob/09f92fab441416e96ef8dfbe2e197cf004270ead/modules/bank)", is it related to this?

**Comment by VitoNaychev** [comment]
How were you able to resolve this error @nezha90? I'm getting the same error when trying to parse some messages from custom cosmos modules.

**Comment by ramiqadoumi** [comment]
@VitoNaychev  put message_type module before messages module in config file
