### ISSUE TITLE
Support for Cosmos SDK v0.50.x

### ISSUE THREAD

**Issue by jmastr** [forbole/bdjuno#745]
## Feature description 

Support for Cosmos SDK v0.50.x

## Implementation proposal

- Update juno to v6 (see https://github.com/forbole/juno/pull/120, thanks @dadamu )
- Update cosmos-sdk to v0.50.6

**Comment by dadamu** [comment]
Hey, you can try this branch:
https://github.com/forbole/callisto/tree/cosmos/v0.50.x

**Comment by jmastr** [comment]
Thanks man! That is just awesome! Thank you so much!

**Comment by wade-liwei** [comment]
hi @jmastr 

I try the 0.50.x version, but I found out the modules register does not execute.

func (r *Registrar) BuildModules(ctx registrar.Context) jmodules.Modules {

So I just see the block and txs in postgre.
Do you know how to enable the modules register.

**Comment by wade-liwei** [comment]
I find out the parameter: 

haha

type ChainConfig struct {
	Bech32Prefix string   `yaml:"bech32_prefix"`
	Modules      []string `yaml:"modules"`
}
