### ISSUE TITLE
Discussion: Block Details query question(s)

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#78]
### Signed voting power

I am trying to query the voting power in a block by using the following query
```
query BlockDetail {
  block(limit: 1, where: {height: {_eq: 314300}}) {
    hash
    timestamp
    num_txs
    validator {
      validator_description {
        moniker
        identity
      }
    }
    pre_commits
    proposer_address
    validator_voting_power_histories_aggregate {
      aggregate {
        sum {
          voting_power
        }
      }
    }
  }
}
```

The result i am getting is the following:
```
{
  "data": {
    "block": [
      {
        "hash": "1C8215F97F09B437E78E4D492EA9E8BF75715621E33D37C651E949EEE64DDBF7",
        "timestamp": "2020-10-26T21:14:51.166442",
        "num_txs": 0,
        "validator": {
          "validator_description": {
            "moniker": "novy",
            "identity": "5422BE13389B2B4D"
          }
        },
        "pre_commits": 88,
        "proposer_address": "desmosvalcons1v5ejtt5dff85c5zfy8gxea25d92yzrw0lewxyw",
        "validator_voting_power_histories_aggregate": {
          "aggregate": {
            "sum": {
              "voting_power": null
            }
          }
        }
      }
    ]
  }
}
```

My expected result is that the `voting_power` sum would not be null. Is this the correct assumption?

---

### Signatures by Block

Is it possible to get a list of signers per block and their sign status (I'm not sure if that makes sense or not)

![image](https://user-images.githubusercontent.com/42913823/104544591-13de0300-5663-11eb-937d-878be0c8c0a5.png)

---
### Side questions

1) Is voting power displayed in udaric?

**Comment by rmontagnin** [comment]
> My expected result is that the `voting_power` sum would not be null. Is this the correct assumption?

Yes, this is correct.

---

> Is it possible to get a list of signers per block and their sign status (I'm not sure if that makes sense or not)

I've change the schema of the `pre_commit` table. You can now get those by using:

```graphql
query Signers($height: bigint) {
  pre_commit(where: {height: {_eq: $height}}) {
    validator_address
    voting_power
  }
}
```

Inside such query you also have access to the `validator` object as well as other validator-related objects.

---

> Is voting power displayed in udaric?

The validator voting power is displayed having measurement unit that is the staking token of the chain. You can get such name using 

```graphql
query Params{
  staking_params {
    bond_denom
  }
}
```

**Comment by ryuash** [comment]
I'm getting an empty array for even at the latest height. Nevertheless i'll set up big dipper to display using the following query first but can you quickly check if that's the expected.
```
query Signers($height: bigint) {
  pre_commit(where: {height: {_eq: $height}}) {
    validator_address
    voting_power
  }
}
```

**Comment by ryuash** [comment]
@RiccardoM For the `sign_status` It seems i need to know who signed/didn't signed for each block. Would that be possible?
