### ISSUE TITLE
Discussion: Review on current queries

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#85]
Let me know if you want me to provide visuals on where the query is being used

### Latest Activities
The timestamp is being used but no longer found in hasura
<details>
<summary>query</summary>

Subscription

```
subscription LatestActivity {
    transaction(limit: 1, order_by: {height: desc}) {
      timestamp
      hash
      height
      messages
      success
    }
  }

```

Query

```
query Activities($limit: Int, $offset: Int, $height: bigint) {
    transaction(limit: $limit, offset: $offset, order_by: {height: desc}, where: {height: {_eq: $height}}) {
      timestamp
      hash
      height
      messages
      success
    }
    transaction_aggregate(where: {height: {_eq: $height}}) {
      aggregate {
        count
      }
    }
  }
```
</details>

---

### Activity Details
The timestamp is being used but no longer found in hasura

<details>
<summary>query</summary>

```
  query ActivityDetails($hash: String) {
    transaction(where: {hash: {_eq: $hash}}) {
      hash
      height
      fee
      gas_used
      gas_wanted
      success
      memo
      messages
      timestamp
    }
  }
```
</details>

---

### Validators Count
Is the following query still valid?
Doing my best to update the queries and I noticed all the history tables are now gone so just double checking
<details>
<summary>query</summary>

```
query Validators {
    active_validators: validator_aggregate(where: {validator_statuses: {status: {_eq: 2}}}) {
      aggregate {
        count
      }
    }
    not_active_validators: validator_aggregate(where: {validator_statuses: {status: {_neq: 2}}}) {
      aggregate {
        count
      }
    }
  }
```
</details>

---

### Validators Staking
~~Is the following query still valid?~~
Not sure what the new query is for the following

<details>
<summary>query</summary>

```
  query ValidatorStaking($address: String) {
    validator(where: {_or: [{validator_info: {consensus_address: {_eq: $address}}}, {validator_info: {operator_address: {_eq: $address}}}]}) {
      delegations {
        amount
        delegator_address
      }
      redelegations {
        src_validator_address
        dst_validator_address
        delegator_address
        amount
      }
      unbonding_delegations {
        amount
        delegator_address
      }
    }
  }
```
</details>

---

**Comment by rmontagnin** [comment]
### Latest activities
The timestamp has been removed from the `transaction` object, and you can find it now inside the `block` object associated to the transaction:

<details>

Subscription
```grapql
subscription LatestActivity {
    transaction(limit: 1, order_by: {height: desc}) {
      block {
         timestamp
      }
      hash
      height
      messages
      success
    }
  }
```

Query

```graphql
query Activities($limit: Int, $offset: Int, $height: bigint) {
    transaction(limit: $limit, offset: $offset, order_by: {height: desc}, where: {height: {_eq: $height}}) {
      block {
         timestamp
      }
      hash
      height
      messages
      success
    }
    transaction_aggregate(where: {height: {_eq: $height}}) {
      aggregate {
        count
      }
    }
  }
```
</details>

### Activity details
Same as above.

### Validators count
The query you've written are correct. 

### Validators Staking
The query you've written is correct

**Comment by ryuash** [comment]
### ~~Validators count~~
~~It feels a bit off since `validator_statuses` is now a history of all their status changes no? So wouldn't i have to find their status change by latest height. But the current query is aggregating them regardless of height.~~

---

### ~~Validators List~~
~~This is the current query I have so far. I think a lot of the tables became a history log so I'm querying the latest info by height.
I'm currently missing the self delegations but I think I want to confirm whats happening with the tables at the moment.~~

<details>
Query

```
query Validators {
  validator {
    validator_info {
      operator_address
    }
    validator_descriptions(order_by: {height: desc}, limit: 1) {
      moniker
      identity
    }
    validator_voting_powers(order_by: {height: desc}, limit: 1) {
      voting_power
    }
    validator_commissions(order_by: {height: desc}, limit: 1) {
      commission
    }
    validator_statuses(order_by: {height: desc}, limit: 1) {
      height
      jailed
      status
    }
    validator_signing_infos(order_by: {height: desc}, limit: 1) {
      missed_blocks_counter
    }
  }
  slashing_params(order_by: {height: desc}, limit: 1) {
    signed_block_window
  }
}
```

![image](https://user-images.githubusercontent.com/42913823/105944366-2104e400-609e-11eb-82d4-93171c975803.png)

</details>

---

### ~~Validator Delegations~~

~~Is the current table a list of the current delegations or is it a history (Asking since the history tables no longer exist)~~
<details>

```
query ValidatorStaking($address: String) {
    validator(where: {_or: [{validator_info: {consensus_address: {_eq: $address}}}, {validator_info: {operator_address: {_eq: $address}}}]}) {
      delegations {
        amount
        delegator_address
      }
      redelegations {
        src_validator_address
        dst_validator_address
        delegator_address
        amount
      }
      unbonding_delegations {
        amount
        delegator_address
      }
    }
  }

```

![image](https://user-images.githubusercontent.com/42913823/105944495-5f9a9e80-609e-11eb-8c2f-e353f3cfd7c5.png)

</details>

---

Below are queries that i'm unsure about

### Validator Activities
How do i get activities by validator/user

<details>

![image](https://user-images.githubusercontent.com/42913823/105945716-c7ea7f80-60a0-11eb-9eeb-9b6394663d17.png)

</details>

---

### Validator Power Events

<details>

![image](https://user-images.githubusercontent.com/42913823/105945805-efd9e300-60a0-11eb-978f-59e0c19a3fc0.png)


</details>

---

### ~~Activities filter by type~~
~~I've tried filtering the other day but it kept coming back empty~~

<details>
I did something like this before the update

```
query LatestActivity {
  transaction(limit: 5, order_by: {height: desc}, where: {messages: {_contained_in: {
    type: "cosmos-sdk/MsgUnjail"
  }}}) {
    timestamp
    hash
    height
    messages
    success
  }
}
```

</details>

---

### User Staking
Below are the wireframe. Let me know if this query is even possible and how to approach it.

<details>
![image](https://user-images.githubusercontent.com/42913823/105946451-44ca2900-60a2-11eb-94b1-5f183372fffd.png)
![image](https://user-images.githubusercontent.com/42913823/105946481-501d5480-60a2-11eb-80d9-e31e360d6c53.png)
![image](https://user-images.githubusercontent.com/42913823/105946509-5c091680-60a2-11eb-8384-8c5fbf7b57c7.png)

</details>
