### ISSUE TITLE
Getting real time consensus states

### ISSUE THREAD

**Issue by kwunyeung** [forbole/bdjuno#86]
## Feature description 

On the home page UI, we have this section which shows the real time consensus state. This is to show whether the chain is making consensus even if the chain is waiting for blocks.
<img width="182" alt="preview-chat-Screenshot 2021-01-27 at 4 43 39 PM" src="https://user-images.githubusercontent.com/932636/105966242-5b32ad80-60bf-11eb-83b2-3beba2c4654e.png">

We will need that data to be provided by the GraphGL endpoint.

## Implementation proposal

The data can be captured by this Tendermint RPC endpoint.

http://rpc.morpheus.desmos.network:26657/consensus_state

As most of the time the consensus will be made if the the prevotes are enough for making consensus (assuming precommits will be the same as the prevotes), we can just get the voted percentage in the `prevotes_bit_array`.

![image](https://user-images.githubusercontent.com/932636/105966845-22470880-60c0-11eb-9a28-6741a6acec7e.png)

The values here mean voting power `99924` out of total `160299` has voted which is around `62%`.

@RiccardoM @ryuash

**Comment by rmontagnin** [comment]
Closing as it's too difficult to implement
