### ISSUE TITLE
Question: transactions query by address

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#87]
Is there a way to query transactions by delegator's address? I see we have a signer info with a pub key now but i'm not sure if that's exactly what i'm looking for.

![image](https://user-images.githubusercontent.com/42913823/106099554-d5be0480-6175-11eb-900f-8b3e48cefdc2.png)

**Comment by kwunyeung** [comment]
@ryuash you can query txs with the `delegator_address` as the structure of the tx is like this

```json
"tx": {
        "@type": "/cosmos.tx.v1beta1.Tx",
        "body": {
          "messages": [
            {
              "@type": "/cosmos.staking.v1beta1.MsgUndelegate",
              "delegator_address": "desmos1fc3mdf0ue2f4suyg5vjj75jtaer0cl0dgqvy6u",
              "validator_address": "desmosvaloper1pr7q92pv395pe2tst24ejkthpfz4w5zsh0zpja",
              "amount": {
                "denom": "udaric",
                "amount": "250000000000"
              }
            }
          ],
          "memo": "",
          "timeout_height": "0",
          "extension_options": [],
          "non_critical_extension_options": []
        },
        "auth_info": {
          "signer_infos": [],
          "fee": {
            "amount": [],
            "gas_limit": "205261",
            "payer": "",
            "granter": ""
          }
        }
```

I think you will be able to query with jsonb like
```
{
 tx:{
    body:{
        messages:{
            "delegator_address":"desmos1fc3mdf0ue2f4suyg5vjj75jtaer0cl0dgqvy6u"
        }
    }
 }
}
```

**Comment by rmontagnin** [comment]
@ryuash If what Kwun's depicted doesn't work, we can try connecting each delegation/undelegation/etc to the proper transaction. This should be easily doable. Let me know if the above method works for your or it's too complicated

**Comment by ryuash** [comment]
@kwunyeung Are we only displaying certain transaction messages in the individual pages? Not all message types have `delegator_address`. I had originally thought we wanted to display **all** transaction messages that were signed by the selected address. Please give me clarification on the activities component in `validator_details` and `user_details`.

@RiccardoM Since i had previously asked about filtering transaction messages by type I thought the current bdjuno isn't able to query/filter jsonb.

I updated the title. I was actually going to see how I can query all transactions initiated by the selected address (both validator and normal delegator addresses)

**Comment by kwunyeung** [comment]
@ryuash I see. To query all transactions, you will have to query base on every message types. Different messages will have different fields in the transactions. Querying the `auth_info` is not enough as you can only get the transactions that are signed by the account but not all that related to the account. The address maybe in the `to_address` in a send or maybe it's in the `withdraw_address`.

**Comment by ryuash** [comment]
@kwunyeung @RiccardoM 
Currently I have no way of querying messages at all.
In the Hasura docs example there is a table with a list of JSONB but in our data structure I get a transactions table with a `messages` key that's contains an array of JSONB. It seems i'm unable to query on that level
![image](https://user-images.githubusercontent.com/42913823/106416799-3c506480-648d-11eb-87d1-c1133a9fca3b.png)

Our Schema:

![image](https://user-images.githubusercontent.com/42913823/106416928-981aed80-648d-11eb-9f9f-d355e502326e.png)


~~Would it be logical/realistic to pull `messages` in to it's own table with a `one-to-many` relationship to `transaction`?~~

**Comment by kwunyeung** [comment]
We may try creating a view for the messages.

https://github.com/hasura/graphql-engine/issues/2468#issuecomment-648160903

**Comment by rmontagnin** [comment]
@ryuash I've added a `message` table. You can query it using 

```graphql
query Messages {
  message {
    index
    transaction {
      hash
    }
    type
    value
    involved_accounts_addresses
  }
}
```

Please let me know if this fixes the issue

**Comment by ryuash** [comment]
@RiccardoM I'm unable to query `involved_accounts_addresses` 

query:

```
query ValidatorActivities {
  message(where: {involved_accounts_addresses: {_in: ["desmosvaloper14dm0zdemeymhayucp7gchuus3k5m344f0p084p"]}}) {
    value
    type
    transaction_hash
    involved_accounts_addresses
    index
  }
}
```

results:

```
{
  "errors": [
    {
      "extensions": {
        "path": "$",
        "code": "constraint-error"
      },
      "message": "type \"_text[]\" does not exist"
    }
  ]
}
```

I found a related github issue https://github.com/hasura/graphql-engine/issues/2797

**Comment by kwunyeung** [comment]
Hasura doesn't support array ATM.

**Comment by rmontagnin** [comment]
@ryuash I've decided to solve this using [Hasura custom functions](https://hasura.io/docs/1.0/graphql/core/schema/custom-functions.html). You can now query messages by a given address and which type is contained in a given array of types: 

```graphql
query MessageByAccount {
  messages_by_address(
    args:{
      addresses:"{desmosvaloper14dm0zdemeymhayucp7gchuus3k5m344f0p084p}",
      types:"{}",
      limit:1,
      offset: 0
    },
  ) {
    type
    involved_accounts_addresses
  }
}
```

**Arguments**
- `addresses`
   Array of addresses which should be searched for. The resulting messages will have the `involved_accounts_addresses` array containing **any** of these `addresses`. This is particularly useful for validators, where you can supply both `desmos1..` and `desmosvaloper1...` addresses here. For accounts, you can simply pass only the `desmos1...` address.  
   Note that this is an array value, and thus it must provided as `{value1, value2, ...}`.  
   This argument is **mandatory** and cannot be skipped.  
   Providing an empty `addresses` will result in an empty result.

- `types`  
   Array of types which should be searched for. The resulting messages will have the `type` that is any of the provided values. This is particularly useful when filtering for module, where you can supply for example `"{cosmos.staking.v1beta1.MsgCreateValidator, cosmos.staking.v1beta1.MsgEditValidator}`.  
   This is an array, thus its value must be provided as `{value1, value2, ...}`.  
   This argument is **mandatory** and cannot be skipped.  
   Providing an empty `types` (`{}`) will result in all types being valid. 

- `limit`  
   Limits the number of resulting rows.  
   This parameter is *optional** with default value `100`. 

- `offset`
   Offsets the limit by the specified amount.  
   This parameter is *optional** with default value `0`. 

**Note**  
All the returned rows are sorted by `height` in a **descending** fashion.

**Comment by rmontagnin** [comment]
Closing this as it had no more discussion to it

**Comment by ryuash** [comment]
@RiccardoM Would it be possible to get the total number of transactions?  Need it for pagination purposes

```
total: transaction_aggregate {
    aggregate {
      count
    }
  }
```

**Comment by ryuash** [comment]
I did a temporary work around until you have time to work on this (or if you can't then just close the issue)

**Comment by ryuash** [comment]
closing as the work around seems pretty stable
