### ISSUE TITLE
Question: User Info query

### ISSUE THREAD

**Issue by YuhsinLiao1995** [forbole/bdjuno#89]
how could i query this?

![截圖 2021-01-28 下午4 51 12](https://user-images.githubusercontent.com/61954949/106113099-09eef080-6189-11eb-8fb1-5fa75746e9c0.png)

this is the query i made now, please help me check if it's correct? not sure how to query  the amount of `available`, `reward`, `commission`, and the `reward address`, `total amount` in $USD?  Thanks

```
query UserInfo {
  account(where: {address: {_eq: "cosmosvaloper14kn0kk33szpwus9nh8n87fjel8djx0y070ymmj"}}) {
    account_balances {
      coins
    }
    delegations {
      amount
    }
    redelegations {
      amount
    }
    unbonding_delegations {
      amount
    }
  }
}
```

**Comment by ryuash** [comment]
The `total_amount` should be 0 as the token right now has no value

**Comment by YuhsinLiao1995** [comment]
@ryuash ok

**Comment by rmontagnin** [comment]
@kwunyeung Can you please explain me what is the `commission` of a user and how do you compute that in the current BigDipper version? Also, how do you compute the `reward` for each user?

**Comment by kwunyeung** [comment]
@YuhsinLiao1995 

The USD amount will only be available if the token is listed on exchanges with a public value.

@RiccardoM 

The `commission` is from the validator commission generated by `x/distribution`. Only validator address would have this `commission`. 

e.g. http://lcd.morpheus.desmos.network:1317/cosmos/distribution/v1beta1/validators/desmosvaloper1pr7q92pv395pe2tst24ejkthpfz4w5zsh0zpja/commission

Protobuf: `cosmos.distribution.v1beta1.Query.ValidatorCommission`


The `rewards` is the total rewards of a delegator. This can be queried with 

http://lcd.morpheus.desmos.network:1317/cosmos/distribution/v1beta1/delegators/desmos1rpurg200edtv6rgvfjuf7j6s8mghnsljkzvurg/rewards

This is all reward of an address from block rewards if `x/mint` is enabled and fee distribution from `x/distribution`.

Protobuf: `cosmos.distribution.v1beta1.Query.DelegationTotalRewards`

**Comment by RiccardoM** [comment]
@YuhsinLiao1995 I've added two tables: `validator_commission_amount` and `delegation_amount`. Now, this query should get you all the data: 

```graphql
query UserInfo($address: String, $height: bigint) {
  account(where: {address: {_eq: $address}}) {
    address
    available: account_balances(where: {height: {_eq: $height}}) {
      coins
    }
    delegations(where: {height: {_eq: $height}}) {
      amount
    }
    redelegations(where: {height: {_eq: $height}}) {
      amount
    }
    unbonding_delegations(where: {height: {_eq: $height}}) {
      amount
    }
    validator: validator_infos(where: {self_delegate_address: {_eq: $address}}) {
      consensus_address
      operator_address
      self_delegate_address
      validator {
        rewards: validator_commission_amounts(where: {height: {_eq: $height}}) {
          amount
        }
        commissions: validator_commission_amounts(where: {height: {_eq: $height}}) {
          amount
        }
      }
    }
  }
}
```

**Comment by rmontagnin** [comment]
@YuhsinLiao1995 I've added the proper tables, you should be able to get the data by using the following query: 

```graphql
query UserInfo($address: String, $height: bigint) {
  account(where: {address: {_eq: $address}}) {
    address
    available: account_balances(where: {height: {_eq: $height}}) {
      coins
    }
    delegated: delegations(where: {height: {_eq: $height}}) {
      amount
    }
    redelegations: redelegations(where: {height: {_eq: $height}}) {
      amount
    }
    unbonding: unbonding_delegations(where: {height: {_eq: $height}}) {
      amount
    }
    rewards: delegation_rewards(where: {delegator_address: {_eq: $address}, height: {_eq: $height}}) {
      amount
    }
    validator: validator_infos(where: {self_delegate_address: {_eq: $address}}) {
      consensus_address
      operator_address
      self_delegate_address
      validator {
        commissions: validator_commission_amounts(where: {height: {_eq: $height}}) {
          amount
        }
      }
    }
  }
}
```

**Comment by YuhsinLiao1995** [comment]
@RiccardoM 

How to query the total amount? or i should sum up `available`, `delegated`... to get the number?
which one is `reward address`?

**Comment by rmontagnin** [comment]
> @RiccardoM
> 
> How to query the total amount? or i should sum up `available`, `delegated`... to get the number?
> which one is `reward address`?

To get the `total` amount you need to sum up together: 
- `available`
- `delegated`
- `rewards`
- `commissions`

The _Reward address_ should be equal to the user `address`, but I'd like to have @kwunyeung's confirmation on this

**Comment by kwunyeung** [comment]
Also `unbonding`.

Yes the address for querying the rewards is the same address as the account. There is a `rewards withdrawal address` but don't mix this up. Account A can set the reward withdrawal address to Account B, which means the rewards belong to A will be withdrawn to B when A broadcast a reward withdrawal message.

**Comment by YuhsinLiao1995** [comment]
got it, thank you @RiccardoM @kwunyeung both

**Comment by ryuash** [comment]
@RiccardoM Is there a way for me to fetch the `rewards withdrawal address`?

**Comment by rmontagnin** [comment]
@kwunyeung Where is the `rewards withdrawal address` present inside Cosmos? How can I get this?

**Comment by kwunyeung** [comment]
@RiccardoM you can get from this endpoint `/cosmos/distribution/v1beta1/delegators/{delegator_address}/withdraw_address`.

And the corresponding method in protobuf is `Query.DelegatorWithdrawAddress` in `x/distribution`.
