### ISSUE TITLE
Feature Request: Add relations from validator to precommits in block height

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#90]
## Implementation proposal

Be able to get a block by block height and a list of validators at that height and their precommit status for that block

**Comment by rmontagnin** [comment]
I've edited the `Block` object by transforming the `pre_commits` from a simple count to the list of pre commits. You should now be able to get it using the following query: 

```graphql
query Block {
  block(where: {height: {_eq: 2}}) {
    pre_commits {
      validator {
        consensus_address
      }
    }
    validator {
      consensus_address
    }
  }
}
```
