### ISSUE TITLE
Question: User Staking

### ISSUE THREAD

**Issue by YuhsinLiao1995** [forbole/bdjuno#91]
how could i query this?
![截圖 2021-01-29 上午11 57 22](https://user-images.githubusercontent.com/61954949/106231406-a1f1e600-622c-11eb-9725-910ed3f75c65.png)
![截圖 2021-01-29 下午12 24 52](https://user-images.githubusercontent.com/61954949/106231603-07de6d80-622d-11eb-83a8-b6d3c57352c2.png)
![截圖 2021-01-29 下午12 24 45](https://user-images.githubusercontent.com/61954949/106231606-09a83100-622d-11eb-8c32-81f1d68246cd.png)

this is the query i made, please help me check if it's correct? not sure how to query  `amt Ratio`,`VP Ratio`, `Last 7 days`  Thanks

```
query UserStaking {
  unbonding_delegation {
    validator {
      unbonding_delegations{
        amount
        validator_address
        height
        completion_timestamp
      }
      validator_commissions {
        commission
      }
    }
  }
  redelegation {
    validator {
      redelegations {
        amount
        dst_validator_address
        height
        completion_time
      }
       validator_commissions {
        commission
      }
    }
  }
  delegation {
    validator {
      delegations {
        amount
        validator_address
      }
      validator_commissions {
        commission
      }
    }
  }
}
```

**Comment by rmontagnin** [comment]
I have no idea what "Amount ratio" and "VP ratio" mean to be honest :sweat_smile: Can we get an explanation of this from @kwunyeung?

**Comment by kwunyeung** [comment]
From what I see here, the `amount ratio` is the self delegation / delegation ratio. The `VP ratio` is the voting power / total voting power ratio.

From the unbonding and redelegation tabs, there is no such "remaining" things. If you unbond 100 tokens, you have to wait 21 days for all 100 tokens. This is how Cosmos chains work. The remaining thing can be something suitable for Solana and V Systems but they have different terms.

**Comment by rmontagnin** [comment]
@YuhsinLiao1995 I think you can get those data from the current tables then? Also, we should probably delete the `Remaining` column all together

**Comment by YuhsinLiao1995** [comment]
@RiccardoM 
ok, i'll remove the `remain` column and` Last 7 days`, and updated the query
