### ISSUE TITLE
Add indexes to the db

### ISSUE THREAD

**Issue by rmontagnin** [forbole/bdjuno#92]
In order to make Hasura go faster, we need to add proper PostgreSQL indexes to the tables that are joined together (e.g on `height` columns, validator's `address`, etc).

**Comment by kwunyeung** [comment]
Please also add GIN indexes for those jsonb fields which the values will be searched. Consider if we need queries that search for existence of a value or just using containment. If we are only using containment operator, we can use `json_path_ops` type. 

And I suggest indexing height in descending orders.
