### ISSUE TITLE
Block voting power greater than bonded tokens at the given height

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#98]
```
query ($height: bigint) {
  pool: staking_pool(limit: 1, where: {height: {_eq: $height}}) {
    bonded_tokens
  }
  pre_commit_aggregate(where: {height: {_eq: $height}}) {
    aggregate {
      sum {
        voting_power
      }
    }
  }
}
```

```
{
  "height": 1000
}
```

results:

```
{
  "data": {
    "pool": [
      {
        "bonded_tokens": 153441285236
      }
    ],
    "pre_commit_aggregate": {
      "aggregate": {
        "sum": {
          "voting_power": 773681
        }
      }
    }
  }
}
```

This would cause the voting power at this given block to be ~504.22% which does not make sense. Feel free to close if this is caused by bdjuno not finished parsing.

![image](https://user-images.githubusercontent.com/42913823/106988889-d6751d00-67ab-11eb-91ef-a71f7475eaf2.png)

**Comment by rmontagnin** [comment]
@kwunyeung Has this ever happend to you?

**Comment by rmontagnin** [comment]
@ryuash Why are you `limit: 1` on `staking_pool`? Does it return multiple lines somehow if you don't specify that?

**Comment by kwunyeung** [comment]
@RiccardoM is the staking pool being recorded on every block height from a non pruning full node? I wonder if the value of bonded tokens is from the correct height.

**Comment by rmontagnin** [comment]
> @RiccardoM is the staking pool being recorded on every block height from a non pruning full node? I wonder if the value of bonded tokens is from the correct height.

Yes, it's being updated every block querying the gRPC of a `pruning: "nothing"` node.

**Comment by ryuash** [comment]
@RiccardoM you gave me this query in the beginning. I've just been reusing it. It doesn't make a difference with or without the limit though. I can remove it later

```
pool: staking_pool(limit: 1, where: {height: {_eq: $height}}) {
    bonded_tokens
  }
```

**Comment by rmontagnin** [comment]
@kwunyeung I've just queried directly from the node, here is the result: 
```shell
$ desmos q staking pool --height=1000
bonded_tokens: "773685514803"
not_bonded_tokens: "402073932734"
```

**Comment by kwunyeung** [comment]
@RiccardoM this is correct. 

Checked the signed voting power at height 1000. The sum queried is correct as well.
http://rpc.morpheus.desmos.network:26657/validators?height=1000

So the issue is on recording the bonded tokens to database at certain height.
