### ISSUE TITLE
Self/Delegation Aggregation allow sum amount

### ISSUE THREAD

**Issue by ryuash** [forbole/bdjuno#99]
## Feature description 

Currently the self/delegation aggregation(s) does not allow amount sums.

![image](https://user-images.githubusercontent.com/42913823/106993754-5902da00-67b6-11eb-9e4c-434f19366c5a.png)

**Comment by rmontagnin** [comment]
This can't be done. Each delegation is a list of coins, and there might be multiple coins with different denominations. The sum would mean summing all amounts for all denominations: 

```js
delegations = [
  { "denom": "udaric", "amount": "50000", "address" "1" },
  { "denom": "uatom", "amount": "20000", "address" "1" },
  { "denom": "udaric", "amount": "5000", "address" "2" },  
];

sum = [
  { "denom": "udaric", "amount": "55000" },
  { "denom": "uatom", "amount": "20000"},
];
```

This should be made inside the UI
